### ISSUE TITLE
Incompatibility with package "svg"

### ISSUE THREAD

**Issue by joaomlourenco** [joaomlourenco/novathesis#102]
David Sousa asked about compatibility problems of this package. To be checked.

**Comment by jmg-duarte** [comment]
If the idea is to render svg's using LaTeX, I *strongly* recommend that David renders the SVG's to PDF and use them instead. 

A "tree" of useful resources:
- https://tintin305.github.io/2019/10/27/SVG-Graphics-LaTeX/
  - https://tex.stackexchange.com/questions/2099/how-to-include-svg-diagrams-in-latex
    - https://mirrors.up.pt/pub/CTAN/info/svg-inkscape/InkscapePDFLaTeX.pdf
