### ISSUE TITLE
Possible command typo - printchapthers

### ISSUE THREAD

**Issue by jmg-duarte** [joaomlourenco/novathesis#109]
I was looking around the source code and found the following command.

https://github.com/joaomlourenco/novathesis/blob/6d895bf0ad2d2dbc981b777a7952c1b5ff9fdcb2/novathesis.cls#L841

Isn't **chapthers** a typo of **chapters**?

**Comment by joaomlourenco** [comment]
Yes it is.  Thanks for pointing out.  Will fix it asap.
