### ISSUE TITLE
Why are there so many warnings, underful boxes on Overleaf?

### ISSUE THREAD

**Issue by pmendoncaphysics** [joaomlourenco/novathesis#111]
I'm using Overleaf to write my PhD and found this nice template.
Nevertheless, why are there are some many warnings, underfull and overfull boxes?
Although it compiles, for a beginner this is a challenge...

![image](https://user-images.githubusercontent.com/63710796/83248359-dc3a4d80-a19c-11ea-8195-66bda27019d9.png)
![image](https://user-images.githubusercontent.com/63710796/83248445-faa04900-a19c-11ea-9fb1-90fbdf4582cf.png)

Here are the Overleaf settings:
![image](https://user-images.githubusercontent.com/63710796/83249024-e01a9f80-a19d-11ea-8310-dc4aa6c5b460.png)

**Comment by joaomlourenco** [comment]
Please read this
https://www.overleaf.com/learn/how-to/Understanding_underfull_and_overfull_box_warnings
