### ISSUE TITLE
Compilation of template.tex in TeXmaker

### ISSUE THREAD

**Issue by pmendoncaphysics** [joaomlourenco/novathesis#112]
Are there any settings to customize in order to compile it in TeXmaker?

I got so many warnings:

![image](https://user-images.githubusercontent.com/63710796/83431756-c0020f00-a42f-11ea-9aa4-e6fa6e5d221a.png)

How to get a clean compilation?

**Comment by joaomlourenco** [comment]
You don't!  :|
Please read this
https://www.overleaf.com/learn/how-to/Understanding_underfull_and_overfull_box_warnings
