### ISSUE TITLE
Mudança de faculdade em \ntsetup{school=ul/ist} dá erro em qualquer faculdade exceto nova/fct

### ISSUE THREAD

**Issue by diogodemilio** [joaomlourenco/novathesis#119]
Tentei testar outras para perceber a extensão do problema e, tanto quanto entendi, todas as faculdades dão erro no seu "default.clo" exceto o da fct, que funciona sem problemas, mesmo quando selecionado no \ntsetup.

Na maioria deles dá um erro semelhante ao apresentado:
"(C:/Users/**(nomeutilizador)**/Desktop/novathesis-master\novathesis-files/Schools/ul/ist/defau
lts.clo

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.125 \renewcommand{\@pnumwidth}
                                {2em}
"

Tentativa de compilação recorrendo ao TeXworks através do MikTex

**Comment by joaomlourenco** [comment]
Qual é a versão em causa?
A versão 5.0.0 e 5.1.0 estavam com bugs.
Hoje de madrugada publiquei a versão 5.1.1 que corrigia (espero) os bugs já encontrados, incluindo as capas das teses.
Pode(s) re-verificar por a nova versão, por favor?  Obrigado.

**Comment by diogodemilio** [comment]
Transferi horas antes de lançar esta incidência. De qualquer forma fui confirmar e a versão que aparece no template.tex é a 5.1.1.
Por curiosidade fui verificar se esta funcionalidade funcionava na versão que usei na altura que redigi a minha tese (4.1.7) e também não funcionava, curiosamente.

**Comment by joaomlourenco** [comment]
Podes por favor verificar a nova versão (5.1.2)?
Diz-me se funcionou bem…
Obrigado.

**Comment by joaomlourenco** [comment]
Problem solved in v5.1.2
