### ISSUE TITLE
Using hyperref and minted packages break the build

### ISSUE THREAD

**Issue by jmg-duarte** [joaomlourenco/novathesis#132]
I'm running `latexmk` as compiler and the document template version is `5.1.10`
```latex
\usepackage{hyperref}
```
Or even 
```latex
\usepackage{minted}
```
Will stop the document from compiling with:
```
Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\\' on input line 398.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\\' on input line 398.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\\' on input line 398.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `math shift' on input line 398.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `math shift' on input line 398.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `math shift' on input line 398.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `math shift' on input line 398.
```

**Comment by joaomlourenco** [comment]
You are listing "Warnings" and not "Errors".    Warnings are not supposed do not break the build.
I also use latexmk and it works.  Can you please confirm that your build is failing and that it is due to those warnings???  Thanks.

BTW; I am aware of those warnings, but did not find (yet) a way to eliminate them!

**Comment by jmg-duarte** [comment]
- Regarding the `minted` package, my extension is at fault
- Regarding the warnings, they can be fixed using the solution described in https://tex.stackexchange.com/questions/10555/hyperref-warning-token-not-allowed-in-a-pdf-string
- Regarding hyperref, I don't think importing it under the final user's feet is a viable solution, not only it disappears from autocomplete, it also stops the user from customizing the package as necessary
I'll be closing the issue as anything else seems unrelated

**Comment by joaomlourenco** [comment]
Please leave this issue open until all the issues are solved.
- I'll check the compatibility problems with the minted package.
- Concerning the PDF warnings, thanks for the suggestion(s).  I'll have  look at it as well.
- Regarding `hyper ref`, I need to load it _before_ the user get's control on the `template.tex`.  But you can always add `\PassOptionsToPackage{<YOUR_OPTIONS_HERE>}{hyperref}` **before** the `documentclass[...]{novathesis}`

**Comment by joaomlourenco** [comment]
BTW, I would appreciate some help if your up for it…  😊

**Comment by jmg-duarte** [comment]
I closed the issue since the problem is no longer related to the title and people searching for the related problem could overlook it.
I'll update the title though.

---

`minted`
---
Compability problems with `minted` seem to be fixed by making use of  `-shell-escape`.
When using `latexmk` (and maybe `lualatex` reason why I can't confirm is in the end) the end user can specify a `.latexmkrc` file with the following content (or add it to an existing one):
```
$pdflatex='pdflatex -shell-escape';
```

The user will also need to add:
```latex
\usepackage[full]{textcomp}
```
To override the existing import without options.
What seems to happen is that `minted` depends on `textcomp` (the `full` version), and the document imports only `textcomp` (normal version), when the compiler reaches the disagreement in imports, it errors out.
The explicit import from the user fixes this.

---

Some other issues may appear regarding the font, `lualatex` does not seem to work with the way `kpfonts` is used.

If the case for `hyperref` is as such, I'd advise to document it in the main file.
Being able to `\usepackage{hyperref}` is nice since it allows my editor to know where to look for completions, but not a requirement.

**Comment by joaomlourenco** [comment]
The template now works with the minted package with the option "-shell-escape" is given in the command line.
