### ISSUE TITLE
LuaTeX & xelatex do not work in Ubuntu 20.04 

### ISSUE THREAD

**Issue by jmg-duarte** [joaomlourenco/novathesis#133]
This is not an *issue* but rather an important note which should be added to the wiki.

Ubuntu 20.04 does NOT ship `kpfonts-otf` and thus LuaTeX/xelatex will not work out of the box.
https://packages.ubuntu.com/focal/all/texlive-fonts-extra/filelist

It seems to me that fixing it can be done as follows:
```bash
wget http://mirrors.ctan.org/fonts/kpfonts-otf.zip
unzip kpfonts-otf.zip
sudo cp -r kpfonts-otf/tex/ /usr/share/texlive/texmf-dist/tex/latex/kpfonts-otf/
sudo cp -r kpfonts-otf/doc/ /usr/share/texlive/texmf-dist/doc/fonts/kpfonts-otf
sudo cp -r kpfonts-otf/fonts/ /usr/share/texlive/texmf-dist/fonts/kpfonts-otf/
sudo ln -s "/usr/share/texlive/texmf-dist/fonts/kpfonts-otf" "$HOME/.fonts/OTF/kpfonts-otf"
mkfontdir ~/.fonts/OTF
mkfontscale ~/.fonts/OTF
fc-cache ~/.fonts
```
At least the error related to `kpfonts-otf` is gone and now a new one related to Helvetica appears

**Comment by joaomlourenco** [comment]
Added to the wiki.  Thanks for the suggestion.
