### ISSUE TITLE
\autoref links are rendered in Portuguese

### ISSUE THREAD

**Issue by jmg-duarte** [joaomlourenco/novathesis#134]
In the document setup I have `\ntsetup{lang=en}`, however the compiler renders the `\autoref` links in Portuguese

Example:
```latex
\autoref{fig:java-mult-typestate} shows the \texttt{Mult} program written in a typestated fashion,
notice that the \texttt{Scanner} type is now augmented with its state.
```
Produces:
![image](https://user-images.githubusercontent.com/15343819/103531950-39f4ed80-4e82-11eb-883c-2a596a11176b.png)

I looked around but found nothing suspect.
I'm using `latexmk`, the command `latexmk -v` prints:
```
Latexmk, John Collins, 26 Dec. 2019. Version 4.67
```

**Comment by joaomlourenco** [comment]
Please confirm that it is working now.  Thanks.

**Comment by jmg-duarte** [comment]
It works! Thank you!
