### ISSUE TITLE
Cover Nova/IMS[BUG] 

### ISSUE THREAD

**Issue by brunagoncalves95** [joaomlourenco/novathesis#144]
Hi!
I'm using the  5.2.1 version of the template, I use MikTek & TexMaker in windows.

I've selected \ntsetup{school=nova/ims} and after compiling it shows up the following error message

" ! Use of \thespecialization doesn't match its definition.<argument> \thespecialization [\option {/novathesis/coverlang}] \ntprintcovers "

Thanks,
Bruna

**Comment by joaomlourenco** [comment]
Hi Bruna,

Thanks for reporting this.  I believe it is fixed now!

Please download the latest version and replace your file "NOVAthesisFiles/Schools/nova/ims/defaults.ldf" with the one from the new version.  Please reopen this issue if this does not fix the problem for you.
