### ISSUE TITLE
[BUG] Table of Contents

### ISSUE THREAD

**Issue by andreffrosa** [joaomlourenco/novathesis#158]
[5.3.1]

The table of contents is including an entry for itself. That is not exactly a "bug" yet it is odd and redundant.

**Comment by joaomlourenco** [comment]
Yes!  Some people want it… some others don't.  Yet, if it is not there, it won't show in the PDF (side) bookmarks as well.  But I'll make it work better soon.  Keeping the "bug".  :)

**Comment by andreffrosa** [comment]
> 
> 
> Yes! Some people want it… some others don't. Yet, if it is not there, it won't show in the PDF (side) bookmarks as well. But I'll make it work better soon. Keeping the "bug". :)


This command:

\pdfbookmark{Contents}{contents}

only adds to the bookmarks on the side and not to the table itself.

If you provide an option to choose between the latter and the following it would satisfy everyone:
\phantomsection
\addcontentsline{toc}{chapter}{Table of contents}%

**Comment by joaomlourenco** [comment]
THat was the plan.  Thanks for the careful instructions.
If you are willing to fix it yourself and submit a pull request, I would be very happy with it.  Otherwise I'll take care of that soon.  :)

**Comment by andreffrosa** [comment]
I'll do it.

**Comment by joaomlourenco** [comment]
@andreffrosa, I'm sorry… I did not see your message and did it myself before going to sleep.
But I would appreciate your collaboration in some other task if you're up for it!  :)
