### ISSUE TITLE
Covers NOVA/FCT [BUG] 

### ISSUE THREAD

**Issue by afap13** [joaomlourenco/novathesis#162]
**Which version of the template are you using?**
I'm using 5.3.1 version.

**Do you use a cloud-based service?  Which one?**
Yes, Overleaf.

**Do you use a local service?**
No.

**What went wrong?**
At line 71 of template.tex file, I can choose the type of document I want. However, when I choose "msc" or "mscplan", the document cover returns to the old cover. I took a look at NOVAthesisFiles/Schools/nova/fct/Images and I noticed that msc covers (cover-msc-std.pdf file) still are the old version while the phd covers (cover-phd-std.pdf file) are the new version of cover. 

**What was expect?**
I was hoping that when I chose "msc" or "msc plan" on line 71 of the template.tex, the cover wouldn't change to the old version.

**Instructions to Reproduce the Error**
1. Uncomment line 71 of template.tex file.
2. Change option to "msc" or "mscplan".
3. The cover will change to old version.

**Screenshots**
![image](https://user-images.githubusercontent.com/78856563/111077112-28b20800-84e7-11eb-83af-972a6a96ad73.png)

**Comment by joaomlourenco** [comment]
I am confused!  
What do you mean by "new version" and "old version" of the cover?

**Comment by afap13** [comment]
Sorry professor, I was making confusion. I did look to the "problem" and I saw that was my confusion. Sorry and thank you for your time. You can close this issue.
