### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RPires7** [joaomlourenco/novathesis#165]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add units to the symbols. 

**Describe alternatives you've considered**
I managed to add the units for the list of symbols. I used the package ( \usepackage{siunitx} ), the glossary style ( \setglossarystyle{altlong4col} ) and  ( \setlength{\glsdescwidth}{0.85\linewidth} ), all in the add your packages here. In the symbols file in the entries i use like this:

\glsxtrnewsymbol[  description={Massa},      symbol={    [ \si{  kg  } ]   }  ]  {m}  {\ensuremath{m}}

the nonumberlist option is on.

**Additional context**

![units](https://user-images.githubusercontent.com/79709523/113291847-8918b600-92eb-11eb-8a40-886803b19583.png)

the version applied was the 5.3.1

**Comment by joaomlourenco** [comment]
Please add your suggestion to the Wiki in this page:
https://github.com/joaomlourenco/novathesis/wiki/adding-units-to-list-of-symbols

Thank you.
