### ISSUE TITLE
[BUG] Cannot disable the glossary and/or symbols

### ISSUE THREAD

**Issue by petersaints** [joaomlourenco/novathesis#166]
**Which version of the template are you using?**
6.2.0 (the current master to be more precise: https://github.com/joaomlourenco/novathesis/commit/06c36f803c1cd0104e038299e9b9c0e34b6f9ac9)

**Do you use a cloud-based service?  Which one?**
No

**Do you use a local service?**
Yes. TeXLive 2020 as packages by Ubuntu 20.10.

**What went wrong?**
I don't use the glossary or symbols on my document. Therefore, I don't them to be included as empty pages at the beggining of my document. On 5.3.2 I was able to comment those files out, but not on 6.2.0. If I do this:
```
%\ntaddfile{glossaries}[glossary]{glossary}
\ntaddfile{glossaries}[acronyms]{acronyms}
%\ntaddfile{glossaries}[symbols]{symbols}
```

I get the following errors:
```
./template.tex:203: Missing endcsname inserted.
<to be read again> 
                   optk@/@nt/file/glossaries/glossary 
l.203 \begin{document}
                              % Beginning of document
The control sequence marked <to be read again> should
not appear between \csname and \endcsname.

./template.tex:203: Extra \endcsname.
<argument> ...file/glossaries/glossary \endcsname 
                                                  
l.203 \begin{document}
                              % Beginning of document
I'm ignoring this, since I wasn't doing a \csname.


./template.tex:203: LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.203 \begin{document}
                              % Beginning of document
You're in trouble here.  Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

NT LOADING “\optk@/@nt/file/glossaries/glossary ” failed
NT LOADING “Chapters/acronyms” succeeded
(./Chapters/acronyms.tex
NT FILE acronyms.tex
)
./template.tex:203: Missing endcsname inserted.
<to be read again> 
                   optk@/@nt/file/glossaries/symbols 
l.203 \begin{document}
                              % Beginning of document
The control sequence marked <to be read again> should
not appear between \csname and \endcsname.

./template.tex:203: Extra \endcsname.
<argument> .../file/glossaries/symbols \endcsname 
                                                  
l.203 \begin{document}
                              % Beginning of document
I'm ignoring this, since I wasn't doing a \csname.


./template.tex:203: LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.203 \begin{document}
                              % Beginning of document
You're in trouble here.  Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

NT LOADING “\optk@/@nt/file/glossaries/symbols ” failed
NT AtEndPreamble ntsetlayout
```

I should mention that I had a similar problem before with early 5.x.y versions: https://github.com/joaomlourenco/novathesis/issues/122
But a newer version of the template eventually fixed the issue.

**What was expected?**
I expected to be able to omit the glossary and symbols, keeping only the acronyms.

**Instructions to Reproduce the Error**
1. Start from a "fresh" distribution of the template
2. Open the Config/6_files.tex file
3. Comment lines 54 and/or 56 like mentioned above.
4. Compile the template.tex file (e.g., by running `latexmk -pdf template`)
5. I get the errors mentioned in "What went wrong?"

**Expected behavior**
I expected that my modifications would produce no errors. That I could include 0, 1, any 2, or all 3 "glossaries" by commenting/uncommenting the lines I mentioned.

**Screenshots**
N/A (I don't think that screenshots are needed given the description I gave)

**Additional context**
I should mention that I had a similar problem before with early 5.x.y versions: https://github.com/joaomlourenco/novathesis/issues/122
But a newer version of the template eventually fixed the issue.

**Comment by joaomlourenco** [comment]
I'm not able to reproduce this bug.
May you _please_ try with the latest version?
Just downlad it and replace the folders  "Config", "Chapters", and "Bibliography" with your worknig folders.
Let me knwo if it still fails…  and if it does, please let me know which version of LaTeX are you using and on which Operating System.  Thanks.

**Comment by petersaints** [comment]
I have just tried it again on Windows 10 with an updated MiKTeX installation and it works well there. Although I had to do a few modifications to the chapter files so that they don't reference the glossary entries that I omitted by supressing the `glossary.tex` and `symbols.tex.

However, on Linux I still have the same issue. I don't even get to the point of having errors due to undefined entries. Perhaps the culprit is the version of TeX Live packaged with Ubuntu 20.10. I hope to take a better look at it soon.

**Comment by petersaints** [comment]
The problem seems to have to do with a different behavior on these definitions on the `novathesis.cls` file:
```
\newcommand*{\@loadglossaryfiles}{%
  \optionlistdo{/@nt/file/glossaries/glossary}{\@ntloadfile@i{##1}}%
  \optionlistdo{/@nt/file/glossaries/acronyms}{\@ntloadfile@i{##1}}%
  \optionlistdo{/@nt/file/glossaries/symbols}{\@ntloadfile@i{##1}}%
}
```

Whereas on my Windows install the unused options get ignored, or at least they don't raise an error. On Linux, they try to load the file anyway using the `/@nt/file/glossaries/glossary` or `/@nt/file/glossaries/symbols` as the default value.

At least that's my interpretation based on this part of the output I placed on the opening post:
```
...
NT LOADING “\optk@/@nt/file/glossaries/glossary ” failed
NT LOADING “Chapters/acronyms” succeeded
...
NT LOADING “\optk@/@nt/file/glossaries/symbols ” failed
...
```

**Comment by petersaints** [comment]
Ok. I just installed TeX Live 2021 and it works. I'll close it now. But it's something worth keeping in mind if someone else faces the same issue on older TeX distributions.
