### ISSUE TITLE
Spacing in List of Algorithms

### ISSUE THREAD

**Issue by jaasilva** [joaomlourenco/novathesis#170]
I'm using version 6.4.0 (local LaTeX installation), with the algorithm package.

I added the list of algorithms to the lists of the template by placing the following in file '8_list_of.tex':
`\netaddlistof{listofalgorithms}`

However, in the list of algorithms, there is no spacing between the chapters (as is in the other lists).

To fix this issue, after some digging in the Internet, I added the following to file '7_packages.tex':
```
\renewcommand{\insertchapterspace}{
	\addtocontents{lof}{\protect\addvspace{10pt}}
	\addtocontents{lot}{\protect\addvspace{10pt}}
	\addtocontents{loa}{\protect\addvspace{10pt}}
}
```
Maybe this is not the best solution, but it works for now...

**Comment by joaomlourenco** [comment]
Please try to replace your definition above with:
```latex
\appto{\insertchapterspace}{\addtocontents{loa}{\protect\addvspace{10pt}}}
```
and let me know if it works all right for you.

**Comment by jaasilva** [comment]
Sorry for the late reply.

Yes, it works perfectly.

> Please try to replace your definition above with:
> 
> ```
> \appto{\insertchapterspace}{\addtocontents{loa}{\protect\addvspace{10pt}}}
> ```
> 
> and let me know if it works all right for you.
