### ISSUE TITLE
List of Algorithms not listed in Table of Contents

### ISSUE THREAD

**Issue by jaasilva** [joaomlourenco/novathesis#172]
I'm using version 6.4.0 (local LaTeX installation).

I added the list of algorithms to the lists of the template by placing the following in file '8_list_of.tex':
\netaddlistof{listofalgorithms}
The list gets printed in the defined order.
However, the List of Algorithms doesn't appear in the Table of Contents (as the other lists do).

To fix this issue, after some digging in the class file, I added the following to file 'novathesis.cls' (the lines marked with ---):
```
\newcommand*{\netaddlistof}[1]{%
  \ifthenelse{\equal{#1}{tableofcontents}}{\options{/@nt/list/listof/.cpush={%
        \iftoggle{/novathesis/tocintoc}{%
            \tableofcontents%
        }{%
            \phantomsection\pdfbookmark[1]{\contentsname}{toctarget}%
            \hypertarget{toctarget}{\tableofcontents*}%
        }%
  }}}{%
    \ifthenelse{\equal{#1}{listsofglossaries}}{\options{/@nt/list/listof/.cpush={%
            \iftoggle{/novathesis/glsxindy}%
                {\printglossaries}%
                {\printnoidxglossaries}%
    }}}{%
      \options{/@nt/list/listof/.cpush={\csuse{#1}}}%
    }%
---    \ifthenelse{\equal{#1}{listofalgorithms}}{\options{/@nt/list/listof/.cpush = {%
---        \addcontentsline{toc}{chapter}{List of Algorithms}%
---  }}}{}
  }%
}
```
Maybe it's not the best workaround, but I was unable to find a more elegant solution.
It works for now...

**Comment by joaomlourenco** [comment]
That's an excellent suggestion.    I'll add it to the template.
