### ISSUE TITLE
Repo banner is cropped too tightly

### ISSUE THREAD

**Issue by jmg-duarte** [joaomlourenco/novathesis#173]
See the figure
![image](https://user-images.githubusercontent.com/15343819/118281599-51458680-b4c5-11eb-954a-e761010ac494.png)

**Comment by joaomlourenco** [comment]
That's weird!  This is what I see… not cropped and a different font!

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2064643/118302676-6974d000-b4dc-11eb-889d-0ff316bbd3f2.png">

I'll check in a Windows system…

**Comment by joaomlourenco** [comment]
Fixed!
