### ISSUE TITLE
Should the default font set be kpfonts?

### ISSUE THREAD

**Issue by jmg-duarte** [joaomlourenco/novathesis#174]
This default font set requires Helvetica, a licensed font which only comes with Macs (according to [this post](https://latex.org/forum/viewtopic.php?p=91055&sid=1ab692e1442087a67e928f6c26f3f0e1#p91055)).

I don't think any of us has the money to buy the [license](https://www.fonts.com/font/linotype/helvetica) and I don't think a college project should advocate for piracy.

Hence I propose that a different default is used and *if possible* made clear which values we can use for which document styles.

For example, if I can use the `bookman` fonts for an MSc Thesis in NOVA FCT.
Similarly, if I can use other chapter styles, etc

**Comment by joaomlourenco** [comment]
Please note that the Helvetica is a _sans serif_ font that is used ONLY for the cover.  The kpfonts are a version of the popular Palatino font (with _serifs._) used in the main text.

But your suggestion is relevant, and I will try to replace the Helvetica with another similar _sans serif_ font.  Maybe the "Gillius" font.   DO you have any suggestion for an alternative font?

**Comment by jmg-duarte** [comment]
Arial is the one that comes to mind but it is also an invalid suggestion as it is mainly for Windows.

The Gillius font seems great!

**Comment by jmg-duarte** [comment]
I took the liberty of trying to replace Helvetica with [Gillius ADF](). I "succeeded" but the "Doe" looks weird, even without the `[Ligatures=TeX]` we get the following:

![image](https://user-images.githubusercontent.com/15343819/118407112-0c615180-b677-11eb-8090-895afe30761c.png)

**Comment by jmg-duarte** [comment]
While I don't know if LaTeX supports it, but the [Inter](https://rsms.me/inter/) font could be a *great* replacement

**Comment by joaomlourenco** [comment]
The “Inter” font is **and excellent replacement** indeed.
Just replaces Helvetica with Inter in all the covers.    👍 
Published v6.4.3 with this change.
