### ISSUE TITLE
[BUG] Keywords on Abstract don't "break" to the next line. They continue outside the margins of the document.

### ISSUE THREAD

**Issue by petersaints** [joaomlourenco/novathesis#175]
**Which version of the template are you using?**
6.4.2

**Do you use a cloud-based service?  Which one?**
No.

**Do you use a local service?**
Yes. I'm using MikTeX on Windows 10.

**What went wrong?**
I upgraded from 6.4.0 to 6.4.2 and noticed that my keywords on the abstract no longer "broke" to the next line. They continue outside the margins of the document.

**What was expected?*
I was expecting for the keywords to automatically break line and continue to next line.

**Instructions to Reproduce the Error**
1. Start from a "fresh" distribution of the template
2. Edit "abstract-en.tex" and add many more keywords to the keyword area.
3. Compile the document
4. Check that the keywords are not breaking line correctly.

**Expected behavior**
I was expecting for the keywords to automatically break line and continue to next line.

**Screenshots**
![Keywords Bug](https://i.imgur.com/xdC66Hw.png)

**Comment by joaomlourenco** [comment]
Fixed.  You just need to download the new "novathesis.cls' from the repo.
