### ISSUE TITLE
Abstract Único 

### ISSUE THREAD

**Issue by HugoSantiago99** [joaomlourenco/novathesis#176]
Se apenas for usado 1 abstract, é levantada a exceção:
The control sequence marked <to be read again> should
not appear between \csname and \endcsname.

**Comment by jmg-duarte** [comment]
Consegues dar mais informação sobre o ficheiro `6_files.tex`? Eu consigo compilar a minha tese com um só abstract

**Comment by HugoSantiago99** [comment]
Não tenho esse ficheiro, talvez por ter usado o template existente no overleaf, sendo assim vou alterar o que tenho.

Obrigado!
