### ISSUE TITLE
Fonts do not render equally across compilers

### ISSUE THREAD

**Issue by jmg-duarte** [joaomlourenco/novathesis#177]
As the title states.
# Lualatex
![image](https://user-images.githubusercontent.com/15343819/118482270-66602680-b70c-11eb-8fa9-26ff6ea45155.png)
# latexmk
![image](https://user-images.githubusercontent.com/15343819/118482323-7e37aa80-b70c-11eb-9d03-cd7a6057621c.png)

**Comment by b-pereira** [comment]
Are you using Latexmk with LuaLaTex?

**Comment by jmg-duarte** [comment]
In the first one, I guess so. I use the VSCode LaTeX Workshop extension and in it, it is called `latexmk (luatex)`

**Comment by b-pereira** [comment]
```
latexmk -pdflatex=lualatex -pdf <texfile>
```

**Comment by jmg-duarte** [comment]
Adding the `-pdf` flag to the compiler command seems to have fixed the issue. Thank you!
