### ISSUE TITLE
[BUG]  \textit{\textbf{word}} dows not work in template (uminho/ee) school

### ISSUE THREAD

**Issue by leoneldca** [joaomlourenco/novathesis#178]
**Which version of the template are you using?**
Version 2021-04-14 [6.3.0]

_The command \textit{\textbf{word}} do not produce an italic and bolded word as expected, by using this model. Please, could you show me how can I fix it?_

**Do you use a cloud-based service?  Which one?** 
No

**Do you use a local service?** 
Yes: I use TexStudio in Linux Ubuntu 20.04

**What went wrong?**
The command \textit{\textbf{word}} do not produce an italic and bolded word as expected, by using this model. Please, could you show me how can I fix it?

**What was expected?**
I expected the word to be shown both italic and bold.

**Instructions to Reproduce the Error**
>Steps to reproduce the behaviour:
>1. Start from a "fresh" distribution of the template
>2. Add packages "X" and "Y"
>3. …
>3. In the main text, add the text "ABC" or the command "XYZ"
>4. See an error

N/A

**Expected behaviour**
>A clear and concise description of what you expected to happen.

N/A

**Screenshots**
>If applicable, add screenshots to help explain your problem.

N/A

**Additional context**
>Add any other context about the problem here.

N/A

**Comment by leoneldca** [comment]
I insert the following lines in newsgott.ldf and it works.
after line 12 and the respective file in the folder
\ntcheckfont{NewsGotT-Bold-Italic.ttf}{https://www.ics.uminho.pt/pt/Comunicacao/Documents/NewsGotT.zip}

and add bold-italic configuration in the same file

\setmainfont{NewsGotT}[
  Ligatures=TeX,
  Mapping=tex-text,
  Path = NOVAthesisFiles/FontStyles/Fonts/,
  Extension = .ttf, 
  UprightFont=n015003t,
  BoldFont=n015006t,
  AutoFakeSlant=0.15,
  BoldSlantedFeatures={FakeSlant=0.15},
  BoldItalicFont=*-Bold-Italic
]

**Comment by joaomlourenco** [comment]
Great!!  😃
I couldn't find a way to make it work!
Thank for sharing the solution. I'll add it to the template.

**Comment by joaomlourenco** [comment]
Un

**Comment by joaomlourenco** [comment]
Unfortunately it does not work! At least for me…  probably you have some additional font (customized by Bruno) that is not available in the package being downloaded.  Aren' tyou?
Which font (.ttf) files do you have in the “ NOVAthesisFiles/FontStyles/Fonts/” directory?

**Comment by joaomlourenco** [comment]
But with a bit of additional research I got it!  The current version in the master branch already supports BoldItalic, i.e.,  ``\textbf{\textit{this will typeset in bold italic}}`` will typeset as **_this will typeset in bold italic_**
