### ISSUE TITLE
Add all CC licenses in the according language to UMINHO template

### ISSUE THREAD

**Issue by b-pereira** [joaomlourenco/novathesis#179]
**Is your feature request related to a problem? Please describe.**
UMINHO copyright statement cannot be changed from the defined Creative Commons Attribution, Non-Commercial and Share-Alike license `cc-by-nc-sa`. UMINHO Guidelines for thesis and dissertations formatting mentions all 6 licences. Also, the license language has to change accordingly to the main language of the document.

**Describe the solution you'd like**
* Add the other Creative Commons licenses, namely:
1. **CC BY** - _Atribution_ 
2. **CC BY-SA** - _Attribution, Share-Alike_ 
3. **CC BY-NC** - _Attribution, Non-Commercial_
4. **CC BY-ND** - _Attribution, Non-Derivative_
5. **CC BY-NC-ND** -  _Attribution, Non-Commercial, Non-Derivative_

* Change the license language automatically.

**Describe alternatives you've considered**
The alternative is to change the `doclicense` package declaration directly.

**Additional context**
UMINHO copyright licences can be custom, e.g., &copy; ALL RIGHTS RESERVED

**Comment by joaomlourenco** [comment]
Closed!
