### ISSUE TITLE
Font Size becomes smaller in UMINHO template

### ISSUE THREAD

**Issue by b-pereira** [joaomlourenco/novathesis#184]
**Which version of the template are you using?**
 Version 6.4.3, UMINHO template

**Do you use a cloud-based service?  Which one?**
N/A

**Do you use a local service?**
N/A

**What went wrong?**
Use the small size font throughout the UMINHO template, from the copyright onwards.

**What was expect?*
Use the normal size font 

**Instructions to Reproduce the Error**
N/A

**Expected behavior**
Use the normal size font throughout the UMINHO template.

**Screenshots**
Check Additinal Context

**Additional context**
Proposed fix by @vascoalramos
![Proposal](https://user-images.githubusercontent.com/38591616/119378686-6f299d00-bcb6-11eb-9825-586190404fed.png)

**Comment by b-pereira** [comment]
I added in the discussion that the way to solve this issue is to enclose the `\small` macro content with curly braces, as well as to enclose the rest with `\normalsize` (I think the `doclicense` package changes the font size, can't remember). @joaomlourenco

**Comment by joaomlourenco** [comment]
Fixed.
