### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by joaomlourenco** [joaomlourenco/novathesis#2]
Much of the documentation (the example text itself) is outdated.  Must be rewritten.

**Comment by bcandeias** [comment]
Hi, I just got here because I wanted to let you know of an inconsistency that I found in the \committee help text. So, how can I help? :)

**Comment by joaomlourenco** [comment]
Hi Bruno.
I've been (sloowwwlllyyy) rewriting the documentation (chapters 1, 2 and 3).
If you feel confident, just make your own changes and push them back to the master repository. Otherwise, create a branch, work on your branch, and submit a mer request later.

BTW, i just added you with permissions to push stuff to the repository.  :)

Cheers.

**Comment by joaomlourenco** [comment]
You may also report issues here (as that one of the "\committee" and I'll try to fix them asap. 
Please create a new issue for each issue.  :)

**Comment by bcandeias** [comment]
I'll try my best to make myself useful! Also, if you want to improve or include any special information/example that rose from a user's doubt or request, and you don't have the time, feel free to leave me an email. Having priorities/objectives makes contribution much easier. :)

Thanks!
