### ISSUE TITLE
[BUG] Uminho template Has a bug on title page

### ISSUE THREAD

**Issue by Metalkiler** [joaomlourenco/novathesis#211]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/39952471/128543475-f1450bc7-b128-4bdb-a12e-42ebfdaa9d20.png">
Check ScreenShot

**Comment by b-pereira** [comment]
Hi, what is the template's version that you are working on?

**Comment by Metalkiler** [comment]
The version I was working is the github one

**Comment by b-pereira** [comment]
> The version I was working is the GitHub one

After I checked, all the University of Minho versions have the same problem. On the right:

![imagem](https://user-images.githubusercontent.com/944511/128565147-d02c8376-a12c-4ee4-8817-d2de0c702ffb.png)

As you can see, there's a pull request of mine, ready for approval with the fix, and to be merged with the `master` branch by @joaomlourenco . You can check the pull request in the link above or the one below:
![imagem](https://user-images.githubusercontent.com/944511/128565690-5d734eef-0d25-4230-8342-54f63445f83d.png)

The new release publication has to be with him (the 6.4.8 version) and I already notified him.
