### ISSUE TITLE
[BUG] "This Organization is currently ineligible to receive donations."

### ISSUE THREAD

**Issue by snovaisg** [joaomlourenco/novathesis#218]
When i press the donations button, this page from paypal shows up.[
![Screenshot 2021-09-16 at 15 06 23](https://user-images.githubusercontent.com/24900912/133627081-f0d94a54-f964-4d76-a549-0c3a03483ee5.png)
](url)

**Comment by joaomlourenco** [comment]
Fixed!  Thank you *very much* for reporting this.
