### ISSUE TITLE
[Clarity] Config/1_novathesis.tex

### ISSUE THREAD

**Issue by snovaisg** [joaomlourenco/novathesis#220]
**Which version of the template are you using?**
v6.5.0

Default comments on multiple options from [Config/1_novathesis.tex](https://github.com/joaomlourenco/novathesis/blob/master/Config/1_novathesis.tex) don't match code.

**Comment by joaomlourenco** [comment]
Can you please submit (or send me by email) a fixed version?  Or at least an annotated version which identify clearly the mismatching comments/options?  Thanks!
