### ISSUE TITLE
How to register a macros file?

### ISSUE THREAD

**Issue by snovaisg** [joaomlourenco/novathesis#225]
### [Question]
I'd like to have a `macros.tex` that only contains macros that are used throughout the chapters.

Example of the contents of a macros file:
`\newcommand{\wxx}{W_{xx}}`
`\newcommand{\wxh}{W_{xh}}`

### [Setup]

The place to "register" such a file seems to be on `Config/6_files.tex` using the command `\ntaddfile`. So i created the file `Chapters/macros.tex` with the respective contents above, and added the following command to `Config/6_files.tex`: `\ntaddfile{glossaries}[macros]{macros}`

### [Unexpected behaviour]
While there are no errors on `Config/6_files.tex`, i've tried using the newly created macros on `Chapters/chapter1.tex` (namely `\wxx` and `\wxh`) but latex doesn't recognize them, so it seems it wasn't properly added :( 

### [Help]
How can i go about this? A simple way would be to use \input{macros} somewhere i imagine?

**Comment by joaomlourenco** [comment]
You cannot input your macros file as a glossary.  

I believe that if you add
"\ntaddfile{chapter}{maxros}"
In first place, before any other chapter, it will work, but I think your macros won't be available in the front matter material.

My advice is to either define your macros in file "7_packages.tex" itself or, in that same file, use "\input{macros.tex}".

**Comment by snovaisg** [comment]
Thank you, it worked!
