### ISSUE TITLE
[NEW SCHOOL]  Add support for FMV-UL

### ISSUE THREAD

**Issue by joaomlourenco** [joaomlourenco/novathesis#239]
**Name and URL of the school to be supported**
Name: Faculdade de Medicina Veterinária da Universidade de Lisboa
URL: http://www.fmv.ulisboa.pt

**Link to the School's rules/models for thesis and/or dissertations**
URL: TBD
As an alternative, please attach the rules/models to the request.

**Link to the School's “Media Kit”**
URL: TBD
As an alternative, please attach high-quality School's logo(s) and other image materials.

**Comment by hugobarroca** [comment]
Here's a link to the school's rules/models for thesis and dissertations:
[http://www.fmv.ulisboa.pt/uploads/2020/12/5fd73e63a7498.pdf](http://www.fmv.ulisboa.pt/uploads/2020/12/5fd73e63a7498.pdf)

Hope it helps, thank you very much for your work :)

**Comment by joaomlourenco** [comment]
@hugobarroca, closed in version 6.9.5.
