### ISSUE TITLE
Better referencing support (and documentation)

### ISSUE THREAD

**Issue by bcandeias** [joaomlourenco/novathesis#24]
The package `hyperref` ships a neat `\autoref` command, which I tend to use, but the case is not consistent (developer choice). I end up using both `\ref` and `\autoref`, depending on whether I'm starting the sentence with it or not, which means that the hyperlinks sometimes appear in numbers, others also in the preceding word (section, figure, tablet, etc.) This can be fixed, but it could be interesting to provide this out-of-the-box in the template, so it would be harmonized and everyone could benefit from it.

I think it should work like the `cleverref` package:
- `\autoref`\- figure, table, section, chapter
- `\Autoref`\- Figure, Table, Section, Chapter.

The used case would be up to the writer.

More information [here](https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing#autoref).

**Comment by joaomlourenco** [comment]
Fixed in a130cef
