### ISSUE TITLE
[BUG] \ntsetup{printcommittee=false} gets ignored and the committee is printed out anyway

### ISSUE THREAD

**Issue by petersaints** [joaomlourenco/novathesis#251]
I'm using v6.6.0 of the template and when I set `\ntsetup{printcommittee=false}` on `1_novathesis.tex` it simply gets ignored. The committee gets printed out anyway.

**Comment by joaomlourenco** [comment]
Please upgrade to the latest version and confirm if the (wrong) behavior persists.

If it does, please provide more information (which `\ntsetup{}` do you have active?) so that I can repeat the wrong behavior myself.  If it doesn't, please close this issue.  Thank you.

**Comment by petersaints** [comment]
I tested with the latest code from the `master` branch which is supposed to be v6.6.2 and the problem persists. I don't know what exactly do you mean by active `\ntsetup{}`. On my `1_novathesis.tex` file I have only uncommented the following lines:
```
\ntsetup{docdegree=phd}
\ntsetup{printcommittee=false}
```

In fact, I only had the first line uncommented but then I noticed that the "Examination Committee" was being printed out despite the fact the `printcommittee=false` being stated as being the default on the comments included in the `1_novathesis.tex` file.

Just to be sure, I also tried to make this change on a clean download of the latest version available from this repository with the same result. Despite  `printcommittee=false` being set, the "Examination Committee" gets printed out.
![Screenshot 2021-11-15 022530](https://user-images.githubusercontent.com/157810/141712556-b1c8cefc-74c5-48e5-85f2-036c01af0188.png)


P.S.: While trying out the clean template I also noticed that by default the PhD template gets used despite being stated in the  `1_novathesis.tex` that the default for `docdegree` is `msc`. This is a minor issue since I was able to switch between the two with no problem on my limited testing.

**Comment by petersaints** [comment]
I can confirm that it is fixed. Thank you.
