### ISSUE TITLE
[FEATURE REQ] Possible incomplete features in regard UMINHO standards

### ISSUE THREAD

**Issue by b-pereira** [joaomlourenco/novathesis#254]
**Is your feature request related to a problem? Please describe.**
 Yes. A PhD thesis submission from the UMINHO's School of Engineering was rejected because the cover, back-cover weren't compliant with the Formatting Standards Guidelines. The spine was missing. The problem was in the 4.2.1 enhanced version for UMINHO in https://github.com/b-pereira/novathesis. However, the problem isn't specific to that template's version, but overall. 

**Describe the solution you'd like**
Firstly, the spine **in the official template** isn't compliant. Secondly, after spending some time trying to understand the problem with the colleague that's finishing the PhD, as far I could understand, the School of Engineering **specified** by email, with the image below with it, that the elements missing should be like that: 

> Process return: The thesis does not comply with the provisions of Dispatch RT 31/2019. Point 3. Missing the cover, back cover and spine of the thesis.

![imagem](https://user-images.githubusercontent.com/944511/141877641-a15106d7-f3ee-41b7-a031-43ff0e577f4a.png)

**Describe alternatives you've considered**
The alternative given to that PhD thesis was to create the cover and back cover, along with the spine, from the official channel, with the provided Adobe Illustrator file for that School in particular. The tool used for editing was Inkscape in Linux. Note that there's the bleeding of 3mm all around with the AI image dimension for the printing company to trim accordingly.

![imagem](https://user-images.githubusercontent.com/944511/148404646-654a284b-61dd-4367-800a-b4e44b16e322.png)

This extra space is only for the printing company and Dispatch RT 31/2019 **does mention that the cover and back cover should have an A4 page size, that is 210 x 297 mm and not 216 x 303 mm.**

 After the file edition,  PDFs were exported and later included directly in the LaTeX file with the package `pdfpages`. The dimensions were — without the 3mm all around — **440x297mm**. *Note that the spine width is 2 cm as it is on the AI file. That looks a lot, but don't mind it. That is for the printing company and depends on the number of pages, the paper thickness and bookbinding type (usually the binding type for these is flat with 4-page signatures glued to the cover) and they do it with the AI file.* **There aren't specifications for spine width in Dispatch RT 31/2019, just the height (A4 page height or 297mm)**
 
 
 The `\includepdf` macro had the `fitpaper` option and the macros `\eject \pdfpagewidth=* \pdfpageheight=*` were used to expand the width of the document, before the front page.

### **_EDIT: In order to mitigate this I created the cover, back cover and spine  [here](https://github.com/b-pereira/UMINHO-PHD-MSc-Covers/releases) and their verse can be added_. The front page can be generated as well to match the cover. As I say there, further customizations will be provided.** Cover and back-cover, and front-page work standalone and with XeLaTeX (because of the usage of PSTricks). If you find it difficult contact me via email [pereirabruno05@gmail.com](mailto:pereirabruno05@gmail.com) or via Facebook PM https://www.facebook.com/pereirabruno05/

**Additional context**
Given that the elements as they are in this version are not to what the UMINHO's Teaching and Research Organic Units are used to, it isn't known to which degree the elements, as they are here, could be accepted (except the spine that it isn't compliant - the 3mm space between the author's name and the title should be corrected). **Regarding this consideration, some preparations for the eventuality of future rejections are, to some degree, in order**.

**Comment by b-pereira** [comment]
In order to know if the cover, back cover, spine and *their respective verses*, as they are available in this template, are correct, I sent emails to proper entities with samples for MSc and PhD. **No response was given to this date.**

**Comment by joaomlourenco** [comment]
@b-pereira, this is a very very very long bug report that should be on discussions and not here.  A bug report must be clear and concise.
May I ask you to, please, comment below with a proper bug-report?  One paragraph for describing the problem, another for describing the proposed solution (if you have one).   If there are multiple (independent) problems, please create new entries, one for each.  Always clear and concise bug reports, please.

**Comment by b-pereira** [comment]
Will do.

**Comment by joaomlourenco** [comment]
Long bug report.  Unclear problem.  Unclear solution.  

If you find it necessary, please open a new issue.  Please *keep it small and simple!*
