### ISSUE TITLE
[BUG] MScPlan, PhDPlan, PhDProp options (BSc and Plain also, but irrelevant) causes this error

### ISSUE THREAD

**Issue by b-pereira** [joaomlourenco/novathesis#256]
> Yes, the advisers are working now!
> Although, there is still one compilation error showing and I don't know if it's important.

![Screenshot from 2021-11-20 15-48-26](https://user-images.githubusercontent.com/47277541/142732621-e370aec1-2457-460f-a103-e85ac64df0c6.png)

> Thank you for your time!

_Originally posted by @devzizu in https://github.com/joaomlourenco/novathesis/issues/255#issuecomment-974669818_

**Version 6.6.7**
**Linux and Overleaf**

The above error appears in Overleaf. In Linux, with Makefile, only crashes. An option for an intermediate report is necessary, both for PhD theses and MSc/MEng dissertations.

**Comment by joaomlourenco** [comment]
Fixed.
