### ISSUE TITLE
[BUG] MSc and PhD have Cover and Ccover with black background, when it should be grey

### ISSUE THREAD

**Issue by vascoalramos** [joaomlourenco/novathesis#258]
**Which version of the template are you using?**
6.7.2

**Do you use a cloud-based service?  Which one?**
Overleaf (both LuaLaTex and XeLaTex) - TeX Live version: 2021

**What went wrong?**
MSc and PhD have Cover and Ccover with black background, when it should be grey

**Screenshots**
![image](https://user-images.githubusercontent.com/38591616/144252070-261da5eb-dc44-473e-a2a6-32bfd6742938.png)

**Comment by joaomlourenco** [comment]
@vascoalramos, esse bug esteve "no ar" apenas poucos minutos.  Tiveste o azar de apanhar essa versão.
Podes por favor tentar com a última versão do github. Penso que deverá estar tudo ok.  Se não estiver, por favor reabre o issue.  Obrigado.
