### ISSUE TITLE
[BUG] - Erro de configuração do Indice de Listagem

### ISSUE THREAD

**Issue by NunoViegasLeal** [joaomlourenco/novathesis#264]
Boa tarde,

Existe um problema de configuração do LaTeX relacionado com um nome errado que é dado ao "Índice de Listagens".
O Índice de Listagem aparece correctamente, contudo todas as páginas seguintes que deveriam ter o cabeçalho a dizer "Índice de Listagem", não o têm.
Também no "índice geral" o "índice de listagem" não aparece.

Por exemplo, na imagem com o "Índice de Tabelas", está tudo correcto. O cabeçalho das páginas seguintes mostram "Índice de Tabelas", como seria esperado.
![imagem](https://user-images.githubusercontent.com/31273963/147589853-dcf894c8-e179-4aaf-9f9e-0158352da96c.png)

Agora na imagem com o "Índice de Listagens", o título está correcto, contudo o cabeçalho em todas as páginas seguintes não o estão.
![unnamed](https://user-images.githubusercontent.com/31273963/147589926-90a25f63-41d8-40d7-b342-05fcd75e763e.png)

No índice normal, o "Índice de Listagem" nem aparece. As setas a vermelho indicam a posição em que deveria ser mostrado o índice de listagem.
![unnamed2](https://user-images.githubusercontent.com/31273963/147589951-79d748af-a5e7-43c2-9a24-754a8bff75da.png)

O que devo de configurar, e quais os ficheiros a alterar, para conseguir corrigir este problema?

Desde já obrigado!

**Comment by joaomlourenco** [comment]
Please use english here…

Which version of the template are you using?

**Comment by joaomlourenco** [comment]
This is not a problem in the most recent version.  The _headings_ were removed in the front matter pages .  There headers only start with Chapter 1.
So I suggest you update your doc to the latest version of the template.  
Please notice that some entries from "1_novathesis.tex" that had "[…]" were changed to "(…)".  So, please, don't just replace the file… be careful with the syntax change.

Please let me know if you had success.

**Comment by NunoViegasLeal** [comment]
Yes, I had success. The lastest version works fine.

Thank you!
