### ISSUE TITLE
[BUG] Degree names for FCT NOVA not overriding general customisation options

### ISSUE THREAD

**Issue by GuilhermeADF** [joaomlourenco/novathesis#274]
**Which version of the template are you using?**
6.9.4

**Do you use a cloud-based service?  Which one?**
Overleaf.

**Do you use a local service?**
No.

**What went wrong?**
A clear and concise description of the *observed* behaviour.
Options for MSc degree name in `Config/9_nova_fct.tex` are not overwiting the degree name customisation in file `Config/3_cover.tex` (it is necessary to comment the lines 49-54).

**What was expect?**
The correct degree name should be filled in in the pdf.
<img width="1017" alt="Captura de ecrã 2022-01-22, às 15 03 41" src="https://user-images.githubusercontent.com/36577631/150643906-023061df-cb6f-40ad-a5d1-c6a3ed716ce5.png">

<img width="1060" alt="Captura de ecrã 2022-01-22, às 14 52 53" src="https://user-images.githubusercontent.com/36577631/150643503-5186af25-edc6-49b8-ac44-5837521018f0.png">

However, if I comment line 50 in the last screenshot it works.

<img width="1186" alt="Captura de ecrã 2022-01-22, às 14 55 19" src="https://user-images.githubusercontent.com/36577631/150643591-3e192be1-6912-4cb4-80df-179d8054549f.png">

**Instructions to Reproduce the Error**
See above.

**Suggestion to Fix the Error**
The easiest way to fix this would be to alert the student to comment the lines in `Config/3_cover.tex`.

**Comment by joaomlourenco** [comment]
@GuilhermeADF, thank you for the report.  It is fixed now (using the stared command version in `Config/3_cover.tex`.
