### ISSUE TITLE
[FEATURE REQ] List of Definitions, Theorems, Propositions, Examples, etc.

### ISSUE THREAD

**Issue by GuilhermeADF** [joaomlourenco/novathesis#276]
**REQUEST FOR SUPPORTING NEW SCHOOLS SHOULD BE MADE WITH THE APPROPRIATE FORM**

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Support for lists for any environment created with command `\newtheorem`, similarly to what exists for tables, figures and algorithms.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by joaomlourenco** [comment]
If you edit `Config/6_list_of` and add `\ntaddlistof{\the_command_to_make_the_listoftheorems}` in the appropriate place (order), it should work.  Please try and let me know.  If it does not, that it is really a bug and must be fixed.

**Comment by joaomlourenco** [comment]
@GuilhermeADF, I made a mistake.  It must be  `\ntaddlistof{the_command_to_make_the_listoftheorems}` without the initial `/`, e.g., `\ntaddlistof{listoftheorems}`

**Comment by GuilhermeADF** [comment]
Thank you, it worked :)
