### ISSUE TITLE
UMinho cover page font sizes are not correct

### ISSUE THREAD

**Issue by dlrsb** [joaomlourenco/novathesis#296]
I noticed that uminho-defaults.ldf (or univ-defaults.ldf in older versions) has a font size of 16pt for the author name and title of dissertation and 11pt for the date. UMinho's [formatting guidelines](https://alunos.uminho.pt/PT/estudantes/Formataes/1_Despacho_RT-31_2019.pdf) state that the author name and the title must have a font size of 17pt, and the date should be 10pt.

**Comment by b-pereira** [comment]
Ya, that's with the maintainer. He took some liberties. 

This is from my version. As you can see it also has the "problem" of TeX point, but I did define that as 10pt. 
![imagem](https://user-images.githubusercontent.com/944511/152609535-4d34295a-4106-41f3-9fc1-e79cf883730c.png)

I added the new scale factor and defined the leading in bp. **The scale factor is only for the font. If the font has the scale factor, it can remain in `pt`. _The leading, however, if using TeX point, perhaps `bp` would be the correct option._**

This is what the command does. `\baselineskip` is the same as the leading. 
```latex
\fontsize{size}{baselineskip}\selectfont
```
![imagem](https://user-images.githubusercontent.com/944511/152611152-a2913a2a-31e9-4375-b6cd-ef556e67594d.png)

**I still have to measure the leading to check if it's correct. But _if everything remains the same_ `bp` will set the leading to that exact value in DTP points.**

![imagem](https://user-images.githubusercontent.com/944511/152610289-70160a4f-4187-4248-833d-169cb6c4e754.png)

**This is how I put mine. This is for the author and title.**
```latex
% Author name and Title of Dissertation
\coveritem[l]{43mm}{%
  \linespread{1.0}
  \fontsize{17pt}{20.4bp}\selectfont{%
  \theauthorname\\[2.7ex]%
  %\fontsize{17pt}{20.4pt}\selectfont%
  \textbf{\covertitle}}%
}
```

**Comment by joaomlourenco** [comment]
When designing the covers, I used the provided example in a background layer and scaled the fonts to match appropriately the given example.  However, I'll add your patch to the template code.  Thanks.

**Comment by b-pereira** [comment]
> % Author name and Title of Dissertation
\coveritem[l]{43mm}{%
  \linespread{1.0}
  \fontsize{17pt}{20.4bp}\selectfont{%
  \theauthorname\\[2.7ex]%
  %\fontsize{17pt}{20.4pt}\selectfont%
  \textbf{\covertitle}}%
}

This patch?

**Comment by joaomlourenco** [comment]
@b-pereira, yes, that patch.   I noticed it si slightly different from the original version (i.e., it merges two _coveritems_, one for author name and another for the document title, into a single _coveritem_.

May I ask you to please check that this _implementation_ is ok and I can simply replay the existing two _coveitems_ with this one?

Thank you.

**Comment by joaomlourenco** [comment]
This issue has been here for long.   It has too much information and in the end in unclear what is the problem.  I'm closing this.  If anyone finds it necessary, you may open a new issue.  *Please keep it small and simple!*
