### ISSUE TITLE
[BUG]  Long title does not fit well into book spine in “nova/fct”

### ISSUE THREAD

**Issue by LuisLeston** [joaomlourenco/novathesis#299]
[6.5.2][Windows][Overleaf]

Boa tarde professor,

Queria imprimir a dissertação mas como o meu título é muito longo, na lombada fica todo "encavalitado" sobre o ano e o nome. 

O que eu queria fazer era alterar o nome da dissertação na lombada mas mantê-lo igual na capa. Sabe se é possível fazer isto?

Desde já obrigado pela atenção :)

**Comment by joaomlourenco** [comment]
See #298.
