### ISSUE TITLE
Examples with charts

### ISSUE THREAD

**Issue by joaomlourenco** [joaomlourenco/novathesis#3]
Create a couple of examples with charts for plotting data.
I believe GNU Plot will be the best option for this.

**Comment by johannesbottcher** [comment]
Why not using package pgfplots?

**Comment by joaomlourenco** [comment]
Advanced users will chose by themselves, and pgfplots is an excellent alternative (I use it myself).
But my goal has always been to ease the LaTeX learning curve, and I don't think pgfplots is a good bet for this.  :)
But will consider it in a section with suggestions.

**Comment by johannesbottcher** [comment]
It uses LaTeX syntax and comes with LaTeX. Gnuplot on the other hand needs to be installed and has an unknown (to a beginner) user interface. For the whole sake of typesetting ready to publish charts and diagrams (data visualization), i would recommend `pgfplots`, other latex-related software would be `asymptote` and `metapost`. 

Data processing on the other hand, *can* be done with gnuplot and various other tools. Each scientist will have its own preference.

**Comment by joaomlourenco** [comment]
Your arguments are definitely good. 
I'll create a couple of examples with pgfplots as well. Or would you be willing to contribute with a short intro, a few examples, and link(s) to pgfplots manual?  :)

**Comment by johannesbottcher** [comment]
Take your pic ;-) http://pgfplots.net/tikz/examples/

Those examples can be very helpful for your users as well.

**Comment by joaomlourenco** [comment]
I'm gonna close this issue, because it has been open for a very long time and no effective contribution was given so that it could be closed successfully.  I'll reopen it again if the need arises.
