### ISSUE TITLE
[FEATURE REQ] "Integrated Master's in ..."

### ISSUE THREAD

**Issue by manel2811** [joaomlourenco/novathesis#306]
I'm requesting that it could be available a way to have "Integrated Master's in ..." in the cover, instead of just "Master's in ..."; and that this possibility could also be available in Portuguese. Thank you!

**Comment by joaomlourenco** [comment]
@manel2811 That can be achieved by defining, in `Config/3_cover.tex`
```latex
\ntdegreename*(pt){Mestrado Integrado em …}
\ntdegreename*(en){Integrated Master in …}

```
