### ISSUE TITLE
[BUG] Subtitle is not displayed

### ISSUE THREAD

**Issue by petersaints** [joaomlourenco/novathesis#311]
**Which version of the template are you using?**
6.9.6 
P.S.: I'm actually using the latest commit from the master branch, but the problem is the same on 6.9.6.

**Do you use a cloud-based service?  Which one?**
No.

**Do you use a local service?**
Yes. MiKTeX on Windows 11.

**What went wrong?**
Even when the subtitle of the thesis is defined using:
`\nttitle(sub,en){Bla Bla Bla}`
It does not show up in the first and second covers.

**Expected behavior**
The subtitle should be displayed below the subtitle just like in previous versions.
I'm actually updating my document from an older version (6.5.x I believe) and it worked on that version.
It also works on version 6.9.4 as shown in the screenshot below.

**Instructions to Reproduce the Error**
1. Start from a "fresh" distribution of the template.
2. The fresh distribution has a default subtitle defined in "Config/3_cover.tex".
3. The subtitle is not displayed in the generated PDF file when you compile the document.

**Screenshots**
![Screenshot 2022-03-05 235659](https://user-images.githubusercontent.com/157810/156903637-163f55df-b565-4dc4-b40e-cbe1413ff786.png)

**Comment by joaomlourenco** [comment]
Will be fixed today.  
Thanks for reporting!

**Comment by joaomlourenco** [comment]
Fixed in v6.9.10.
