### ISSUE TITLE
[BUG/FEATURE REQ.] Customize the title of the "Symbols" and "Acronyms" sections

### ISSUE THREAD

**Issue by GilOliveira** [joaomlourenco/novathesis#322]
**Which version of the template are you using?**
6.9.10 (2022-03-06)

**Do you use a cloud-based service?  Which one?**
No.

**Do you use a local service?**
MacTex/TeX Live (TeX Live utility version 1.53) on macOS Monterey 12.2.1. TeX packages up-to-date from repositories as of 2022-03-27.

**What went wrong?**
The acronyms chapter is called "Acronyms" and the the the symbols section "Symbols".  Some programmes do favour other terminologies in their guidelines.

**Expected behavior**
As per the [official dissertation guidelines of the NOVA School of Science & Technology MSc programme in Biotechnology (in Portuguese)](https://github.com/joaomlourenco/novathesis/files/8358148/Indicacoes.sobre.a.elaboracao.da.Dissertacao.do.Mestrado.em.Biotecnologia.pdf), those sections should be called "List of Abbreviations" and "List of Symbols", respectively. As such, there should be an option in the configurations files to override the default titles to match the ones supplied by the official documents.

**Instructions to Reproduce the Error**
1. Compile a document with acronyms and/or symbols sections.

**Screenshots**
<img width="512" alt="image" src="https://user-images.githubusercontent.com/1360438/160293244-eb4f7bbc-c6ee-40b9-a45d-4d812ea69d46.png">

**Additional context**
Marking this as a bug just because it's a discrepancy between the template and official guidelines, even though it's a minor one and it only concerns the guidelines of a specific MSc programme.

Also, technically, ["abbreviation" is a broader term that seems more applicable to this context](https://en.wikipedia.org/wiki/Acronym#Nomenclature). [APA style does also seem to favour the term, although not exclusively](https://apastyle.apa.org/style-grammar-guidelines/abbreviations/definition).

Implementation suggestion:
```latex
\ntsetup{acronymstitle="List of Abbreviations"}
\ntsetup{symbolstitle="List of Symbols"}
```

**Comment by joaomlourenco** [comment]
@GilOliveira 
How to rename "A" to "B" is a recurrent support question, and what people want to rename changes a lot.  Still, asking how to change the name of those lists is among the most common questions of this type and I'll consider your suggestion.  Probably I'll use another syntax easier to implement, but that will be equivalent…
```latex
\ntsetup{title/acronyms="List of Abbreviations"}
\ntsetup{title/symbols="List of Symbols"}
```

**Comment by GilOliveira** [comment]
> @GilOliveira How to rename "A" to "B" is a recurrent support question, and what people want to rename changes a lot. Still, asking how to change the name of those lists is among the most common questions of this type and I'll consider your suggestion. Probably I'll use another syntax easier to implement, but that will be equivalent…
> 
> ```
> \ntsetup{title/acronyms="List of Abbreviations"}
> \ntsetup{title/symbols="List of Symbols"}
> ```

Works too! I only made this suggestion because it came from the official guidelines, and so it made sense for it to have a setting dedicated to it.

**Comment by joaomlourenco** [comment]
@GilOliveira 
The most recent version "6.9.12" now supports the easier redefinition of important strings with
```latex
\ntlangsetup{LANG/MACRO=New value}
```
for example
```latex
\ntlangsetup{pt/contentsname=O Índice}
\ntlangsetup{en/listfigurename=The List of Figures}
```

**Comment by GilOliveira** [comment]
Awesome! Thanks!
