### ISSUE TITLE
[BUG / HELP] Glossaries extra error, prints error message in pdf.

### ISSUE THREAD

**Issue by VascoBastos** [joaomlourenco/novathesis#324]
**Which version of the template are you using?**
last version

**Do you use a cloud-based service?  Which one?**
Overleaf

**What went wrong?**
Error in acronyms and symbols, it only says the following:

![image](https://user-images.githubusercontent.com/95321254/160459429-dc290722-946b-4f67-9546-13c13479f7c3.png)

Already tried a new template same error.

Also with automaker, same error.

Can someone help?

**Comment by VascoBastos** [comment]
yes, it happened with a fresh copy of the template. Last night, I solved it. It appears that all folders and files need to be in the  root.

**Comment by joaomlourenco** [comment]
Thanks for posting the fix!  
I think I never tried to have the template in a sub-folder in Overleaf.  I'll try to find what's the problem in this 
case.
