### ISSUE TITLE
[BUG] There is an error in uminho-defaults.ldf

### ISSUE THREAD

**Issue by joaosilvagmr** [joaomlourenco/novathesis#325]
![image](https://user-images.githubusercontent.com/45174736/160565966-cd438fb1-3e39-48e3-a16c-92cf2bb1baed.png)

Line 235, fontsize 1417pt, should be 17pt.

This was triggering a error printing the cover.

**Comment by b-pereira** [comment]
That might be a merge error! I'm on my way.
