### ISSUE TITLE
List of List of Algorithms > character inserted

### ISSUE THREAD

**Issue by poliveiraIPB** [joaomlourenco/novathesis#344]
Hi, Im using the List of Algorithms. Configured in this way:

`\ntaddlistof{tableofcontents}    % The Table of Contents. Probably you want ot leave this as is! ;)
\ntaddlistof{listoffigures}      % The List of Figures. Comment to omit.
\ntaddlistof{listoftables}       % The List of Tables. Comment to omit.
%\@ifpackageloaded{algorithm2e}   % The List of Algorithms for package “algorithm2e”.
 %   {\ntaddlistof{listofalgorithms}}{}   % The List of Algorithms for Algorithm2e
\@ifpackageloaded{algorithm}    % The List of Algorithms for package “algorithms”.
    {\ntaddlistof{listofalgorithms}}{}
\@ifpackageloaded{listings}      % The List of Listings for package “listings”.
    {\ntaddlistof{lstlistoflistings}}{}
\@ifpackageloaded{minted}        % The List of Listings for the “minted” package.
    {\ntaddlistof{listoflistings}}{}
\ntaddlistof{listsofglossaries}  % The Glossary, and the lists of Acronyms and Symbols
`

But the Index always shown a > character after the last index item.

![list_alg](https://user-images.githubusercontent.com/14893611/183402950-d1160cee-7691-4f36-a19d-f3eb27ca2c02.png)

**Comment by joaomlourenco** [comment]
That because you have the ">" somewhere! :)
Which test editor are you using? If it allows to do a global search (in all the files), search for ">" inside the folder "Chapters". I believe you'll find it. Let me know...

**Comment by poliveiraIPB** [comment]
I already do that, and I have no character. 
t will only appears when I enable the list of algorithms.
I will also try with only one algorithm line, and it will appears.
Also without any algorithm it will appears as the image.


So must be something on the list of algorithms generation.

![Captura de ecrã 2022-08-09, às 10 03 51](https://user-images.githubusercontent.com/14893611/183609965-fb6e542b-2bd6-4acb-992c-0cad5fea1577.png)

**Comment by joaomlourenco** [comment]
Humm… which version are you using?  Please update to the latest version (please be aware of the change in the way keywords are written in the abstract) and let me know if you still have the same problem.

**Comment by poliveiraIPB** [comment]
> Humm… which version are you using? Please update to the latest version (please be aware of the change in the way keywords are written in the abstract) and let me know if you still have the same problem.


Hi, i upgrade now to the last version [6.10.1]. 

And the problem remains.


I think i  found a bug.

At 6_list_of.tex

You have:
`\@ifpackageloaded{algorithms}    % The List of Algorithms for package “algorithms”.
    {\ntaddlistof{lstlistoflistings}}{}`

But for me only work with:

`\@ifpackageloaded{algorithm}    % The List of Algorithms for package “algorithms”.
    {\ntaddlistof{listofalgorithms}}{}`


Because the package i use is: algorithm
And if i stay with lstlistoflistings, the list is show wit title List of Listings, and the > character is not show.

But when I change to listofalgorithms, the character > appears.

**Comment by poliveiraIPB** [comment]
I found the error at novathesis.cls line 867.


![Captura de ecrã 2022-08-17, às 11 54 38](https://user-images.githubusercontent.com/14893611/185102096-3fb4db24-ad72-434b-8124-cb1d9c82a7da.png)

**Comment by joaomlourenco** [comment]
@poliveiraIPB thank you for the bug report and bug diagnosis!  👍 
Also, thanks for the note on the `\listofalgorithms`.  I fixed the file `Config/6_list_of.tex`.  Hope everything is ok now.
