### ISSUE TITLE
[BUG] what's wrong with the copyright page?

### ISSUE THREAD

**Issue by AndressaO96** [joaomlourenco/novathesis#354]
Template Version: [v6.10.3]
cloud-based service: no
LaTeX distribution: TEX studio
operating system: Windows 10

Does anybody know what happened to the copyright page in the latest template version? 
Now it only shows the copyright symbol at the top of the page.
![Sem Título](https://user-images.githubusercontent.com/82115517/190530127-d25ef4f9-9760-4b15-a5e7-1972f2cf894d.png)

**Comment by joaomlourenco** [comment]
Yes… weird stuff did happen.  Sorry!  Working on it!

**Comment by AndressaO96** [comment]
First of all, thank you so much for “novathesis” LaTeX template!!!!!
Of course there is no need for apologies. Thanks for answering!

**Comment by joaomlourenco** [comment]
Fixed in the latest (v6.10.5) version. :)
