### ISSUE TITLE
[BUG] Italics in nttitle (might be a naïve question)

### ISSUE THREAD

**Issue by degoldschmidt** [joaomlourenco/novathesis#360]
**Which version of the template are you using?**
Forked Version 2022-05-16 [6.10.4]

**Do you use a cloud-based service?  Which one?**
No, local.

**Do you use a local service?**
Yes, TeXLive PdfTeX Version 3.141592653-2.6-1.40.24 (TeX Live 2022).

**What went wrong?**
Using \textit or \itshape within nttitle leads to compilation error.

**Expected behavior**
Italics used within a subset of words the title like _Drosophila melanogaster_

**Instructions to Reproduce the Error**
1. Start from a "fresh" distribution of the template
2. Add \textit{XYZ} to nttitle
3. See error

**Screenshots**

**Additional context**

**Comment by joaomlourenco** [comment]
@degoldschmidt 
Fixed in version 6.10.7.
