### ISSUE TITLE
[BUG] Isel template doesn't compile

### ISSUE THREAD

**Issue by jsaramago** [joaomlourenco/novathesis#381]
**Which version of the template are you using?** 6.10.12
Checkout the repo, defined the school as ISEL (`\ntsetup{school=ips/isel}`), run make and this is the output:
```
Redoing nameref's sectioning
Redoing nameref's label

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\<def>-command' on input line 203.


Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\<def>-command' on input line 203.


Package todonotes Warning: The length marginparwidth is less than 2cm and will
most likely cause issues with the appearance of inserted todonotes. The issue c
an be solved by adding a line like \setlength {\marginparwidth }{2cm} prior to
loading the todonotes package. on input line 203.

(/usr/local/texlive/2019/texmf-dist/tex/latex/psnfss/t1phv.fd)

! Package pdftex.def Error: File `\@school@logo@memory .pdf' not found: using d
raft setting.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.211 \ntprint{covers}
                            % The cover page
```
**Do you use a cloud-based service?  Which one?** No

**Do you use a local service?** Yes, mactex, Mac OS 11.6.7 

**What went wrong?**
Doesn't compile

**Expected behavior**

**Instructions to Reproduce the Error**
1. Start from a "fresh" distribution of the template
2. Add packages "X" and "Y"
3. …
3. In the main text, add the text "ABC" or the command "XYZ"

**Screenshots**

**Additional context**

**Comment by joaomlourenco** [comment]
ISEL is IPL and not IPS.  😃
```latex
\ntsetup{school=ipl/isel}
```

**Comment by jsaramago** [comment]
Sorry for the typo, even when I put `\ntsetup{school=ipl/isel}` I get the same error

**Comment by joaomlourenco** [comment]
Ah!  That's weird. Because I get that error with "ips/isel", but everything works all with with "ipl/isel".
Please double check… if the errors persists, please let me know which LaTeX distribution (and version) you are using. Thanks.

**Comment by joaomlourenco** [comment]
Definitely cannot reproduce the bug. It works on my machine!  😁

**Comment by joaomlourenco** [comment]
@jsaramago 
I was testing with the _develop_ branch and not the _master_.
Updated the _master_ to match _develop_.  Please check again.

Please let me know if it worked or still fails.  Thanks.
