### ISSUE TITLE
[Feature Req] Add support for Greek language

### ISSUE THREAD

**Issue by mkiatos** [joaomlourenco/novathesis#391]
Is it possible to add support for writing the abstract also in Greek language?

**Comment by joaomlourenco** [comment]
Hi @mkiatos,

Definitely yes!  But I never used non-latin alphabets with my template.
Are you using "pdflatex". "xelatex" or "lualatex"?
How do you usually do to write in greek?  (babel + input encoding + font encoding + …)

Just because I'm curious… what is your host university?

**Comment by joaomlourenco** [comment]
I think I did it…. :)
The greek text is from "Google Translate" and can be totally weird.
<img width="1372" alt="Screenshot 2022-12-04 at 23 20 22" src="https://user-images.githubusercontent.com/2064643/205521896-0d6f41dd-cccb-4868-9dcc-5e871f9eddbd.png">

**Comment by joaomlourenco** [comment]
May I ask your help to translate the strings in the following file to greek?
[strings-gr.txt](https://github.com/joaomlourenco/novathesis/files/10149734/strings-gr.txt)

And also the abstract file (that I made with Google Translate)?
[abstract-gr.txt](https://github.com/joaomlourenco/novathesis/files/10149741/abstract-gr.txt)

**Comment by mkiatos** [comment]
Thanks a lot for the quick response. I have a problem with this syntax '\ntaddfile{abstract}[gr]{abstract-gr}'. When I change the language to {gr} the greek abstract disappears.  I will attach the translated files in the coming days.

**Comment by mkiatos** [comment]
> Hi @mkiatos,
> 
> Definitely yes! But I never used non-latin alphabets with my template. Are you using "pdflatex". "xelatex" or "lualatex"? How do you usually do to write in greek? (babel + input encoding + font encoding + …)
> 
> Just because I'm curious… what is your host university?

I am from Aristotle University of Thessaloniki.

**Comment by joaomlourenco** [comment]
> I am from Aristotle University of Thessaloniki.

Would you like some help with the thesis cover and other settings/regulations?

**Comment by mkiatos** [comment]
Yes it would be great if you can help me with that. The cover should be something like that 
![cover](https://user-images.githubusercontent.com/20087464/206221605-180710dd-8e91-47d8-9c79-e778e70f1fd0.png)

**Comment by joaomlourenco** [comment]
I will do the cover it next week.
Still working on the details to support Greek properly.

**Comment by joaomlourenco** [comment]
@mkiatos can you please answer to te question above?
Also, can you send me links to to a few PhD thesis and MSc dissertations from your school/department/…?  So that I can understand how the documents look like!

**Comment by joaomlourenco** [comment]
@mkiatos 
Just for reference, there is already some basic support for Greek in version 7 of the template, but further validation is needed.
Due to the lack of support from your side, I'm going to close this issue.
If you are still interested, please let me know (or reopen the issue).  Thanks.
