### ISSUE TITLE
[BUG]  rules from `booktabs` only cover first column of a table

### ISSUE THREAD

**Issue by tpdsantos** [joaomlourenco/novathesis#402]
**Version 6.9.6**
When creating a table using the `tabular` environment and using `\toprule`, `\midrule` and `\bottomrule` these rules are only applied in the first column.

**Do you use a cloud-based service?  Which one?**
No

**Do you use a local service?**
pdfTeX Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

**What went wrong?**
When I create a table using `tabular` and add `\toprule`, `\midrule` or `\bottomrule`, these rules only cover the first column.

**Expected behavior**
The `booktabs` rules should cover all columns in the table.

**Instructions to Reproduce the Error**
Starting from a fresh distribution of the template from 6.9.6 version, add to `5_packages.tex`:
```latex
\usepackage{booktabs}
```

In the main text, add:

```latex
\begin{table}[bt!]
  \centering
  \caption{System and column parameters of the GSSR set-up.}
  \begin{tabular}{lrl}
    \toprule
    Parameter & Value & Units \\
    \midrule
    $V_x$ & 4.5 & ml \\
    $L_c$ & 10.0 & cm \\
    $D_c$ & 1.0 & cm \\
    $\epsilon_t$ & 0.6 & - \\
    Pe & 300.0 & - \\
    \bottomrule
  \end{tabular}
\end{table}
```

The result is this:

![image](https://user-images.githubusercontent.com/32461027/210814875-04b832f7-8209-41a9-8aef-3645464848e0.png)

And the result should be this:

![image](https://user-images.githubusercontent.com/32461027/210815266-70f25ae6-8010-4710-9102-f1664ea9e874.png)

**Additional context**
Regarding `booktabs`, I only have this issue with the `novathesis` template, if I create a simple document with booktabs the rules work without any issue.

**Comment by joaomlourenco** [comment]
This works for me in version 6.9.6.
You must be introducing some error somewhere.  Please search for errors in your `template.log` file.

**Comment by tpdsantos** [comment]
Which latex version did you use for testing?With the version I am using, only the 6.9.6 version works, everything else above that does not work...

**Comment by joaomlourenco** [comment]
I'm using TexLive 2022.
Why don't you upgrade for a newer TeXLive distribution?

**Comment by tpdsantos** [comment]
With Ubuntu 20.04 LTS the installed version is TexLive 2019. I'm finishing my PhD in March so I don't want to do any upgrades until then...

Anyway, I found a workaround that works, thanks anyway!

**Comment by tpdsantos** [comment]
In every table, instead of using the booktabs rules, I use the subrules macro `\cmidrule{n-m}` where `n` and `m` are the start and end columns of the rule. The only hassle with this is that you have, in every table, insert the number of columns of that table. The best workaround I got was to add this to your preamble:

```latex
\renewcommand{\toprule}{\cmidrule[1.0pt]}
\renewcommand{\midrule}{\cmidrule}
\renewcommand{\bottomrule}{\cmidrule[1.0pt]}
```

For me the thicknesses look practically the same as the top rules. In the table itself, you would introduce it in this way:

```latex
\begin{table}[bt!]
  \centering
  \caption{System and column parameters of the GSSR set-up.}
  \begin{tabular}{lrl}
    \toprule{1-3}
    Parameter & Value & Units \\
    \midrule{1-3}
    $V_x$ & 4.5 & ml \\
    $L_c$ & 10.0 & cm \\
    $D_c$ & 1.0 & cm \\
    $\epsilon_t$ & 0.6 & - \\
    Pe & 300.0 & - \\
    \bottomrule{1-3}
  \end{tabular}
\end{table}
```

You have to adapt the column numbers everytime you create a new table.

**Comment by joaomlourenco** [comment]
Thank you for sharing your experience.
