### ISSUE TITLE
[BUG]  - Chapter Style (with solution found)

### ISSUE THREAD

**Issue by ailton-moreira** [joaomlourenco/novathesis#435]
**Which version of the template are you using?**
Version 7.0.0 has a small bug in the chapter style setup. 

**Do you use a cloud-based service?  Which one?**
Yes, overleaf.

**Do you use a local service?**
No.

**What went wrong?**
A clear and concise description of the *observed* behaviour.
I want to apply a different style setup to the chapter number. The default option is bar. 
Version 7.0.0 has the following config:
``` \ntsetup{style/chap=bar}```
As I want to use the elegant chapter number style I changed it to 
```\ntsetup{style/chap=elegant}```
But the compilation was falling every time that I tried to compile. And if I had to comment on that line it compile again.

**Expected behavior**
The project should compile and added the style elegant to the chapter number, but it was failing on compiling.

**Instructions to Reproduce the Error**
1. File 1_novathesis uncomment ```\ntsetup{style/chap=bar}```and change to ```\ntsetup{style/chap=elegant}```
2. Then try to compile the project.

**Solution found**
I went to the old versions to compare the changes. I noticed that the name of the chapter was different.
previous versions ```\ntsetup{style/chapter=elegant}```

new version: ```\ntsetup{style/chap=elegant}```

Then I changed the new version to ```\ntsetup{style/chapter=elegant}```

The project compiles again and it adds the chapter number elegant style to the chapter.

Hope this solution is helpful :)

**Comment by joaomlourenco** [comment]
@ailton-moreira 
The “ter” in “style/chapTER” was definitely removed by mistake.  Thanks for noticing and for the correction.
