### ISSUE TITLE
[FEATURE REQ] Add option that just print the second cover

### ISSUE THREAD

**Issue by zigzaghumor** [joaomlourenco/novathesis#450]
**Is your feature request related to a problem? Please describe.**
Some unspported schools don't require the first cover and back cover.

**Describe the solution you'd like**
A toggle that makes just print second cover possible. There exists similar requset like https://github.com/joaomlourenco/novathesis/discussions/447#discussioncomment-6425088

**Comment by joaomlourenco** [comment]
Just to be clear. You want the second cover only (which still depends onde the school) and not the first?  Can you help me understand what problem/difficulty this option would solve?

**Comment by zigzaghumor** [comment]
> You want the second cover only (which still depends onde the school) and not the first
Yes, but I found that commenting the "cover" related section in `nova-fct-defaults.ldf` works, so this request becomes a nice to have but not necessary one.

**Comment by joaomlourenco** [comment]
It is still unclear to me why one wold want that.  But that can be achieved by uncommenting
```latex
\ntaddfile{cover}[1]{cover-front}  % front cover
\ntaddfile{cover}[N]{cover-back}   % back cover
```
at the bottom of `Config/3_files.tex` and create the above files with just one `%` character inside.
