### ISSUE TITLE
[BUG] Abstract order not working for UMinho

### ISSUE THREAD

**Issue by ribeiropdiogo** [joaomlourenco/novathesis#454]
**Version: 7.0.3**

When using the school uminho/ee school option, the abstract order cannot be changed. The document language is set to English and the abstract order is set to EN - PT, but the order remains always PT - EN. For the default school (nova/fct), the issue does not occur.

**Do you use a cloud-based service?**
No

**Do you use a local service?**
Yes.
*LaTeX distribution*: pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
*OS*: MacOS 13.4.1

**What went wrong?**
When compiling the document for the uminho/ee school, I'm not able to change the abstract order in any way. The document language is set to English, and I even used the abstract order setting. Nothing works. However, if I change the school to the default option, nova/fct, the abstract order works.

**Expected behavior**
The abstracts should be order as defined in the abstract order setting.

**Instructions to Reproduce the Error**
1. Start from a "fresh" distribution of the template
2. Change the school to uminho/ee
3. Add the required fonts for uminho
3. Uncomment and change the *lang* option to en
4. Uncomment and change the *abstractorder* to {en,pt}
5. Compile using Makefile
6. See the abstract order (pt,en)

**Comment by joaomlourenco** [comment]
The abstract order for “uminho” is always PT, EN.  This is true no matter the main language of the document is PT or EN.  At least it was the last time I checked.  So… for uminho, the option “abstractorder” takes no effect.

Can you please confirm that the above is still true?  It it is not true, the I can easily reactivate the effect of "abstractorder" for uminho.  :)

**Comment by ribeiropdiogo** [comment]
Yes, that is indeed true. The official order for the University of Minho is PT, EN.

 I was just attempting to change that order, and thought that there was a bug. Sorry for opening an unnecessary issue. :(
 
 Thanks for the quick response!
 
 Note: I was digging through the uminho-defaults file and discovered what you just said. I will use that to do what I was looking for.
