### ISSUE TITLE
ISEL - Mestrado em Engenharia Biomédica - Regras

### ISSUE THREAD

**Issue by NoronhaC** [joaomlourenco/novathesis#470]
**Name and URL of the school to be supported**
Name: Instituto Superior de Engenharia de Lisboa
URL: https://www.isel.pt/

**Link to the School's rules/models for thesis and/or dissertations**
URL: []([]([](https://www.isel.pt/curso/mestrado/mestrado-em-engenharia-biomedica)))
As an alternative, please attach the rules/models to the request.

**Link to the School's “Media Kit”**
[MEB_CapaVersaoProvisoria_TFM.docx](https://github.com/joaomlourenco/novathesis/files/13007993/MEB_CapaVersaoProvisoria_TFM.docx)
[MEB_FolhaRosto_TFM.docx](https://github.com/joaomlourenco/novathesis/files/13007998/MEB_FolhaRosto_TFM.docx)
[MEB_Regras_Escrita_TFM_v20170905.pdf](https://github.com/joaomlourenco/novathesis/files/13008001/MEB_Regras_Escrita_TFM_v20170905.pdf)
[MEB_CapaVersaoDefinitiva_TFM_v

URL: 
As an alternative, please attach high-quality School's logo(s) and other image materials.

![logo_1](https://github.com/joaomlourenco/novathesis/assets/135113777/5c2a0f3b-23cf-4e70-8163-0bc67e7fd098)
![logo_2](https://github.com/joaomlourenco/novathesis/assets/135113777/d9fa26d9-5b33-4ea2-936c-3ca8888027ec)
02.docx](https://github.com/joaomlourenco/novathesis/files/13008003/MEB_CapaVersaoDefinitiva_TFM_v02.docx)

**Comment by joaomlourenco** [comment]
Closed in commit "f206a8c".
