### ISSUE TITLE
NOVA IMS Templates are outdated.

### ISSUE THREAD

**Issue by pdrleal** [joaomlourenco/novathesis#471]
**Which version of the template are you using?**
The last version.

**Do you use a cloud-based service?  Which one?**
Yes, Overleaf

**Do you use a local service?**
No.

**What went wrong?**
The NOVA IMS template is not updated with the last available version.

**Expected behavior**
It is expected to have the most recent template version.

**Instructions to Reproduce the Error**
1. Start from a "fresh" distribution of the template
2. Load NOVA IMS Msc template

**Screenshots**

New word template cover image:

<img width="402" alt="new_thesis" src="https://github.com/joaomlourenco/novathesis/assets/56687816/f455b72b-f822-47a9-8649-37af9e184078">

If necessary, I can provide with the word template document.

**Comment by joaomlourenco** [comment]
Yes please.
Although I can't promise when I'll address this matter.

**Comment by pdrleal** [comment]
> Yes please. Although I can't promise when I'll address this matter.

Okay, thank you!!
The word template is attached in this response.
[Thesis_Template_MDSAA_ENG_25092023.docx](https://github.com/joaomlourenco/novathesis/files/13166309/Thesis_Template_MDSAA_ENG_25092023.docx)

**Comment by joaomlourenco** [comment]
Templates for all the masters of NOVA IMS.
[Mestrado Master templates 2024.zip](https://github.com/user-attachments/files/17060216/Mestrado.Master.templates.2024.zip)

**Comment by pdrleal** [comment]
Thanks Professor!

**Comment by joaomlourenco** [comment]
@pdrleal 
There was a misunderstanding here. 
I did not implement the templates yet. 
I just added a ZIP file with the **Word** version of a few other masters form NOVA IMS.
