### ISSUE TITLE
[FEATURE REQ]  Atualização das capas de PhD do IST

### ISSUE THREAD

**Issue by RafaelaMateus** [joaomlourenco/novathesis#500]
Solicito a atualização das capas para o documento de Doutoramento do IST, quer a versão provisória, quer a versão final.  
Detalhes:
A versão provisória tem apenas 1 página e contra capa branca. 
A versão definitiva tem uma capa geral e contra capa branca, seguida de uma capa detalhada e contra capa branca.

Envio em anexo os ficheiros em pdf com os exemplos da capar provisoria, da capa definitiva e as normas gerais das teses do IST.

Obrigada pela atenção.
RMateus

[normas-para-apresentacao-da-tese-rules-for-phd-thesis-1.pdf](https://github.com/joaomlourenco/novathesis/files/15210611/normas-para-apresentacao-da-tese-rules-for-phd-thesis-1.pdf)
[modelo-capa-tese-provisoria-thesis-cover-model.pdf](https://github.com/joaomlourenco/novathesis/files/15210612/modelo-capa-tese-provisoria-thesis-cover-model.pdf)
[modelo-capa-definitiva-tese-de-doutoramento.pdf](https://github.com/joaomlourenco/novathesis/files/15210613/modelo-capa-definitiva-tese-de-doutoramento.pdf)

**Comment by joaomlourenco** [comment]
@RafaelaMateus, can you please upload the norms for the MSc thesis as well?  I would deal with both simultaneously.  Thanks.

**Comment by joaomlourenco** [comment]
@RafaelaMateus, I just checked and the draft cover is ok.  

To get the "white back page", uncomment the option
```latex
\ntsetup{media=paper}         % The target media for the PDF
```

I will deal with the final versions soon.
Once it is done, uncommenting the same option will get you the "white back pages" for the main cover and the detailed cover.

I'll let you know here when the final covers are ok.

**Comment by joaomlourenco** [comment]
Solved in version 7.1.27.
Please update to the latest version.

**Comment by RafaelaMateus** [comment]
Thank you for the quick answer!
