### ISSUE TITLE
[BUG] : Dedicatory not printing

### ISSUE THREAD

**Issue by ElectroQuanta** [joaomlourenco/novathesis#503]
Hi,

I'm using v7.1.27:
- with xelatex or lualatex
- on Manjaro (6.6.26)
- with texlive 2023.66594-20

I'm writing my MSc dissertation (UM-EE) and I can't print the dedicatory.
I've checked the formatting guide for UM and it does not mention a dedicatory.
But it also does not mention a quote, but I can print it.
Is this expected behaviour?
 
 I'm compiling with `make lua`, but I also tried `latexmk  -pdflua -shell-escape  template.tex`
 

1_novathesis.tex
```
\ntsetup{doctype=msc}       % The type of document
\ntsetup{school=uminho/ee}    % The school id
\ntsetup{docstatus=final}     % The status of the document
```

4_files.tex
```
% File with the dedicatory text. Will only be considered for final documents,
%   i.e., "bsc", "msc" and "phd", otherwise, it will be silently ignored
%   syntax: \ntaddfile{dedicatory}{filename}
\ntaddfile{dedicatory}{dedicatory}
```

Chapters/dedicatory.tex
```
\typeout{NT FILE dedicatory.tex}%

\begin{ntdedicatory}

To my parents
\end{ntdedicatory}
```

Thanks in advance.
Best regards

**Comment by joaomlourenco** [comment]
The dedicatory is explicitly ignored for Univ. Minho.
If you really want to add the dedicatory, add the following to `Config/5_packages.tex`
```latex
\printorder(frontmatter,final):={%
  statement;       % The statement page
  copyright;       % (*) The copyright page
  dedicatory;      % (*) Print the dedicatory
  acknowledgements;% (*) Print the acknowledgments
  quote;           % (*) Print the quote
  abstracts;       % Print abstracts in multiple languages.
  alllistof;       % Print all the listof defined in “6_list_of.tex”
  printglossaries; % Print the Glossary, Acronyms, Symbols, etc…
}

\printorder(frontmatter,provisional):={\theprintorder(frontmatter,final)}
```

Let me know if it worked for you.

**Comment by ElectroQuanta** [comment]
Thanks for the answer.

It did not work, but you already enlightened me.
If it is explicitly ignored, I'll leave it as default :)
