### ISSUE TITLE
Problem with biblatex, citations not found

### ISSUE THREAD

**Issue by lcferme** [joaomlourenco/novathesis#510]
Hello, 

II am trying to use the beautiful template you have generated to write my PhD thesis, but I am having issues with the bibliography. 

I downloaded the latest version of the NOVAthesis template from your repo and I am using a local LaTeX installation (TeX Live 2024). I have just run it on my TexMaker editor on MacOS to check if it was compiling correctly, but, unfortunately, I get this error:

Package biblatex Warning: citation 'Artho04'
(biblatex) was not found at all in the .bbl file,
(biblatex) bibliography labels cannot be generated,
(biblatex) please correct the citation.

and 

LaTeX Warning: There were undefined references.
Package biblatex Warning: Please (re)run Biber on the file:
(biblatex) template
(biblatex) and rerun LaTeX afterwards.

I get it for all the citations present in the template manual as it is. I still get the pdf document, but without the proper citations and bibliography. 

![Screenshot 2024-08-15 at 12 22 19](https://github.com/user-attachments/assets/6e44f3d6-cd8c-420b-83c7-13ef373fd1d2)

Since I am just getting this error without even having modified any document yet, perhaps you can just check if there is an issue with the current version? It seems like it is not accessing the bibliography.bib file, but I am not sure in which document the bug might be.

Looking forward to your reply, cause I would really like to use your template!

Cheers,
Lu

**Comment by joaomlourenco** [comment]
You are using `bibtex` to process the bibliography.  You need to use `biber`.  Please check in google how to configure your editor to use `biber`.  I strongly suggest that you "compile" with `latexmk` that does all the magic behind automatically.
