### ISSUE TITLE
[NEW SCHOOL] - PhD for ISEG student

### ISSUE THREAD

**Issue by halcaide97** [joaomlourenco/novathesis#512]
**Name and URL of the school to be supported**
Name: ISEG
URL: https://www.iseg.ulisboa.pt/

**Link to the School's rules/models for thesis and/or dissertations**
URL: https://www.iseg.ulisboa.pt/secretaria/wp-content/uploads/sites/8/2023/07/8a_modelo-capa-e-folha-de-rosto.pdf
As an alternative, please attach the rules/models to the request.

**Link to the School's “Media Kit”**
URL: https://www.iseg.ulisboa.pt/secretaria/wp-content/uploads/sites/8/2023/07/8a_modelo-capa-e-folha-de-rosto.pdf
As an alternative, please attach high-quality School's logo(s) and other image materials.

**Comment by joaomlourenco** [comment]
Hello.

You just sent part of the information.  

The only regulation you have (for MSc and PhD thesis) is on the aspect of the covers? **Nothing else?**

BTW, the média kit is here:
https://www.iseg.ulisboa.pt/en/about/media-and-brand-identity/

I'm quite busy these days.  How urgent is this request?  :)

**Comment by joaomlourenco** [comment]
@halcaide97 
Do you believe the cover and *folha de rosto* are ok like this?
If not, please let me know what is wrong/missing.

![image](https://github.com/user-attachments/assets/7bd2610b-2ef1-4fd0-9653-d524ca4b326e)
![image](https://github.com/user-attachments/assets/14b2ea6a-10b2-4827-95e8-9952edc56140)

**Comment by halcaide97** [comment]
Perfeito!
Obrigado

**Comment by joaomlourenco** [comment]
Ok.  I just pushed `ulisboa/iseg` to the repository.
Please download the latest commit and select `school=ulisboa/iseg` in ffile `Config/1_novathesis.tex` and try it out.
I believe some minor tweaks will be necessary so, please, let me know what you changed and/or if you need further assisance.
