### ISSUE TITLE
[BUG] LISTAS DE Equações, lista de abreviaturas e de simbolos

### ISSUE THREAD

**Issue by PMSR98** [joaomlourenco/novathesis#517]
ola boa tarde, não estou a conseguir que me apreça as listas de equações, abreviaturas e de símbolos.
será que me consegue ajudar?

**Comment by joaomlourenco** [comment]
1. Please use English in this forum.
2. Please read the instructions on how to submit a question/bug and provide the proper info so that we can help you.  Examples: version of the template? university/school? does it show up in the "original" version when you download the template? do you have any compile errors or just warnings? etc…

**Comment by PMSR98** [comment]
Hello, 
i'm using the last version for NOVA FCT
original version?? didn't understand that....
I'm trying to print de list of equations, symbols and acronyms....
i don't have any erros when recompiled....

**Comment by PMSR98** [comment]
Can we meet at teams to show whats happening ?

**Comment by joaomlourenco** [comment]
Original version is the version as downloaded from the repository (or as a new template in Overleaf).
Those lists are there…
1. Start from the original (clean) version of the template and add some stuff (e.g., one acronym), compile the template a check if it shows up in the acronyms page.  If it does not, either you have some error or *you are not using the acronym in the main text* (unused acronyms do not show up in the list).
2. Do the same for the others (gloassary, etc).
3. When you have a **list of** with one of each, then you can proceed and add the rest of your stuff.

**Comment by PMSR98** [comment]
Symbols and acronyms are ok 
but list of equations doesn't show up....

**Comment by joaomlourenco** [comment]
Equations have no names.  What do you want the "list of equations" to list?

**Comment by PMSR98** [comment]
Yes, you are right!

But in symbols list the description isn't showing up.....  

i have a red box saying: "You haven't specified the entry description"
