### ISSUE TITLE
Making our own chapter styles using preexistent ones

### ISSUE THREAD

**Issue by tfcorreia** [joaomlourenco/novathesis#62]
I've tried to make my own chapter style from bianchi and it worked while working on a blank document. I made a test.clo file with the following:
`\makechapterstyle{test}{%`
	`\chapterstyle{bianchi}`
	`\renewcommand*{\chapnumfont}{%`
		`\normalfont\small\bfseries\flushright}`
	`\renewcommand*{\chaptitlefont}{%`
		`\normalfont\large\bfseries\flushright}`
	`\renewcommand*{\printchapternum}{\flushright\chapnumfont \thechapter}%`
`}`

and then saved it under ChapStyles folder. When I call this style from template.tex, under documentclass[chapstyle=test]{novathesis} it seems like I'm doing nothing at all or worst.

Is there something I'm missing?

**Comment by joaomlourenco** [comment]
I would say you did everything right!
I'll check it myself later in the afternoon and will be back to you on this.

**Comment by joaomlourenco** [comment]
Solved!  :)

Move your 2nd line
"\chapterstyle{bianchi}"
for AFTER the last closing brace (as the list line of your test.clo file).

**Comment by tfcorreia** [comment]
Thank you!

It does work, but `\setlength\beforechapskip{0pt}` and `\setlength\midchapskip{0pt}` do not trigger (I added them yesterday just before I left). I'm looking to modify the spacing in order to gain some more space to write.
