### ISSUE TITLE
Erro na compilação pdflatex

### ISSUE THREAD

**Issue by jorgefdm** [joaomlourenco/novathesis#63]
Olá,

Desde já obrigado pelo template, vou com certeza utilizá-lo para a minha tese.

Corre tudo bem e está tudo muito bem estruturado com a excepção do erro na linha 284 do template.tex:

\printotherlists

O erro é:

! Incomplete \iftrue; all text was ignored after line 284.
<inserted text> 
                \fi 
l.284 \printotherlists
                       	% If option 'otherlistsat=front', print other lists ...

?  
! Missing \endgroup inserted.
<inserted text> 
                \endgroup 
l.284 \printotherlists
                       	% If option 'otherlistsat=front', print other lists ...

? 
! Missing } inserted.
<inserted text> 
                }
l.284 \printotherlists
                       	% If option 'otherlistsat=front', print other lists ...

? 
! Missing } inserted.
<inserted text> 
                }
l.284 \printotherlists
                       	% If option 'otherlistsat=front', print other lists ...

? 
[25] [26]
! Extra \fi.
<argument> ...matter \else \printotherlists@i \fi 
                                                  
l.284 \printotherlists
                       	% If option 'otherlistsat=front', print other lists ...

Suspeito que tenha a ver com o código implementado no .cls que começa na linha 879.

Uso macTeX.

Obrigado

**Comment by joaomlourenco** [comment]
Olá,

Este é o segundo report que me apresentam com este problema. Mas a outra pessoa estava a utilizar o ShareLaTeX.

Preciso de ajuda a diagnosticar o problema:
— qual é a versão do que está a usar?
— fez modificações?
— se fizer download da última versão e processar (sem alterar nada) também obtém o mesmo erro?

Obrigado.
João L.

**Comment by jorgefdm** [comment]
Olá,

Obrigado pela resposta. Sim, mudei várias coisas.

Fiz download mais uma vez e sem mudar nada processa sem erros a primeira vez. Processando uma segunda vez sem mudar nada, aparece o erro. Se limpar os ficheiros auxiliares e voltar a processar não obtenho erro nenhum.

A minha versão é a TexLive-2015.

Obrigado,
JM

**Comment by joaomlourenco** [comment]
Ah!  TexLive 2015…  ;)

Instale o TexLive 2016 (o 201 está quase a sair mas ainda não saiu) e depois atualize os pacotes todos com o "TeXLive Utility". O problema deverá desaparecer.

(Admito que estou curioso em saber qual é o pacote que está a quebrar a integridade do sistema… vou ver se um dia desses consigo instalar um TeXLive 2015 para experimentar…)

**Comment by jorgefdm** [comment]
Obrigado,

Perfeito ... Funciona tudo
