### ISSUE TITLE
[Request] Adicionar suporte para as escolas do ISCTE

### ISSUE THREAD

**Issue by af-silva** [joaomlourenco/novathesis#65]
Eu vou tentar implementar, não sei se terei muito sucesso mas seria interessante serem adicionadas mais escolas a este grande trabalho. Desde já o meu obrigado por esta base!

**Comment by joaomlourenco** [comment]
Caso não tenha sucesso, se me fornecer os elementos gráficos e as normas do ISCTE eu posso fazer isso.  :)

**Comment by af-silva** [comment]
Caro @joaomlourenco eu ainda estou aprender como o latex funciona logo serei um pouco mais lento. Deixo aqui caso tenha então algum tempo as normas gráficas para a [ISTA ](https://www.iscte-iul.pt/assets/files/2017/06/12/1497257192353_ISCTE_IUL_NormasHamonizacaoGrafica_ISTA.pdf)em especifico mas na [página ](https://www.iscte-iul.pt/conteudos/estudantes/informacao-academica/mestrado/926/entrega-de-dissertacao-ou-trabalho-de-projeto)também pode encontrar as restantes escolas. Quanto aos elementos gráficos o ISCTE mudou a sua página e com isso não fui capaz de encontrar os encontrar... antigamente podiam ser encontrados [aqui](http://arquivo-portal.iscte-iul.pt/en/servicos/image_and_communication_office/Identidade_Visual.aspx). 

Novamente obrigado! ;)

**Comment by joaomlourenco** [comment]
Caro André Silva. 
Infelizmente não consegui tratar deste assunto no passado recente.
Assumo que já terá terminado a escrita da sua dissertação/tese, certo?

**Comment by af-silva** [comment]
Caro @joaomlourenco, não tem qualquer problemam sim já. 
Acabei por recorrer a uma versão latex disponibilizada por um aluno de doutoramento (Miguel Duarte). O template que utilizei contem as normas gráficas utilizadas pelo ISCTE à data mas penso que tenham mudado. Eu assim que tiver alguma disponibilidade posso tentar adaptar esse template para que possa também fazer parte deste projeto. 
Caso queira fechar este tópico poderá este issue ou deixar aberto com flag **enhancement** para promover`/extender o suporte também ao ISCTE.

Obrigado.

**Comment by joaomlourenco** [comment]
Sim… fui verificar e realmente houve mudanças recentes.
Vou ver se consigo adicionar o suporte para as novas regras.  Ou talvez possamos fazer isso os dois um dia destes!  :)

(Já agora, será que podia fazer o favor de me enviar o template que anunciam no site do ISCTE nest página?  
[](https://www.iscte-iul.pt/conteudos/estudantes/informacao-academica/percurso-academico/area-mestrado/926/entrega-de-dissertacao-ou-trabalho-de-projeto)
pois é preciso autenticação!  Obrigado.)

**Comment by af-silva** [comment]
Teria todo o gosto em conseguir ajudar mas o meu conhecimento ao nível dos templates é nenhum para ser muito sincero, aprendi o suficiente para conseguir resolver os problemas que me foram aparecendo durante o processo de escrita da dissertação e de alguns artigos. Não dei continuidade na altura ao tópico e acabei por não contribuir por não ter muito tempo disponível e como me foi disponibilizado o template que referi acabei por não dedicar esforço em adaptar este (que serviu de base durante algum tempo par a minha aprendizagem e primeiros passos no latex).

O disclaimer da tempalte que usei disponibilizada pelo Miguel Duarte
```latex
%% This is file `Thesis.cls', based on 'ECSthesis.cls', by Steve R. Gunn
%% generated with the docstrip utility.
%%
%% Created by Steve R. Gunn, modified by Sunil Patel: www.sunilpatel.co.uk
%% Further modified by Miguel Duarte: http://miguelduarte.pt
``` 
Entrei em contacto via e-mail, espero que ajude.
Obrigado novamente.

**Comment by joaomlourenco** [comment]
There is some basic support now (for the old cover layout).  I'll update to the new one upon request.
