### ISSUE TITLE
[Issue] Error while using `caption` and `subcaption` packages

### ISSUE THREAD

**Issue by syphirint** [joaomlourenco/novathesis#66]
When using:

    \usepackage{caption}
    \usepackage{subcaption}

declared in the `template.tex` and 

    \begin{figure}[htbp]
     	\centering
     	\begin{subfigure}{0.4\linewidth}
     		\centering
     		\includegraphics[width=0.5\linewidth]{image}
     		\caption{Test A}
     	\end{subfigure}%
     	\begin{subfigure}{0.4\linewidth}
     		\centering
     		\includegraphics[width=0.5\linewidth]{image}
     		\caption{Test B}
     	\end{subfigure}
     	\caption{Figure caption.}
     	\label{fig:image1}
    \end{figure}

in any chapter, it returns 

[![errors][1]][1]

While using a MWE like this, it works:

    \documentclass{article}

    \usepackage[demo]{graphicx}
    \usepackage{caption}
    \usepackage{subcaption}

    \begin{document}

    \begin{figure}[htbp]
    	\centering
    	\begin{subfigure}{0.4\linewidth}
    		\centering
    		\includegraphics[width=0.5\linewidth]{image1}
    		\caption{Test A}
    	\end{subfigure}%
    	\begin{subfigure}{0.4\linewidth}
    		\centering
    		\includegraphics[width=0.5\linewidth]{image1}
	    \caption{Test B}
     	\end{subfigure}
     	\caption{Figure caption.}
     	\label{fig:image1}
    \end{figure}

    \end{document}

So, is there some incompatibility or is it some bug?

  [1]: https://i.stack.imgur.com/JY0gu.png

**Comment by joaomlourenco** [comment]
The NOVAthesis template is based in the "memoir" class.  This class already provides its own subfigure environment.  You should use it.  See the example of figure 3.1 in page 12, which contains two subfigures.
