### ISSUE TITLE
Symbol list - Glossary entry `a_frontal' has not been defined.

### ISSUE THREAD

**Issue by tfcorreia** [joaomlourenco/novathesis#68]
While trying to implement symbol list, it warns me that the test term "a_frontal" is not defined. Currently I have this in thesis.tex:

`% The Table of Contents is always printed.
% The other lists below may be commented and omitted.
\addlisttofrontmatter{\listoffigures}	% The List of Figures. Comment to omit.
\addlisttofrontmatter{\listoftables} 	% The List of Tables. Comment to omit.
%\addlisttofrontmatter{\lstlistoflistings}	% The List of Code Listings. Comment to omit.
%\addlisttofrontmatter{\printnoidxglossaries}
\addlisttofrontmatter{\glsnogroupskiptrue\setlength{\glsdescwidth}{0.8\textwidth}\printnoidxglossaries}	% The Glossary and List of Acrnonyms
%\addlisttofrontmatter{\printnoidxglossary[type=acronyms, style=acronym_long3col]} 
%\addlisttofrontmatter{\printnoidxglossary[type=symbolslist, style=formel_altlong4colheader]}`

I recall \gls{a_frontal} in text when it's defined in symbols.tex.
I have made 0 changes regarding symbol list in packages.clo.

Am I missing something?

**Comment by outbound-pt** [comment]
It can beat number of things. A lost curly bracket "{}", a character in a different encoding, etc.

To go about debugging it comment that entry in the symbols list and eliminated the text that invokes it and compile to see if everything else is OK.

If so recreate the "a_frontal" entry in symbols list from scratch (no copy paste) and try to compile again.

**Comment by tfcorreia** [comment]
I've tried something else: I copy-pasted the content in symbols.tex into glossary.tex and now I have a Symbols list. However, the list isn't formatted as it should, looking at the code:

![symbol](https://user-images.githubusercontent.com/28350831/28269520-476c5ddc-6afa-11e7-8974-09040634c306.PNG)

Posting the symbols.tex content:

`\newglossaryentry{a_frontal}{name=\ensuremath{a},
description={Frontal area per volume},
symbol={[mm^{-1}]},
sort=Afrontalareapervolume,
type=symbolslist}`

**Comment by joaomlourenco** [comment]
The character "_" is special in LaTeX and can only be used in math mode.  You should not use it in the "name" used in the key of the acronym.  
Try to use "aftrontal" or "aFrontal" and let us know if it still fails.
Note: remember to trash the auxiliary files before trying with the new key.

**Comment by tfcorreia** [comment]
I changed it to "afrontal", "aFrontal" and "aftrontal". The error was always the "not defined" one.
Maybe the symbols.tex isn't being loaded? Whenever I put the symbol in another .tex, like glossaries.tex, it tends to show, with no SI units and anything.

**Comment by tfcorreia** [comment]
Already solved the problem of Units and all using this code:

```
\newglossary[slg]{symbolslist}{syi}{syg}{Symbols List}
  \setacronymstyle{long-short}
  \glsaddkey{unit}{\glsentrytext{\glslabel}}{\glsentryunit}{\GLsentryunit}{\glsunit}{\Glsunit}{\GLSunit}

\newglossarystyle{symbunitlong}{%
\setglossarystyle{long3col}% base this style on the list style
\renewenvironment{theglossary}{% Change the table type --> 3 columns
	\begin{longtable}{lp{0.6\glsdescwidth}>{\centering\arraybackslash}p{2cm}}}%
	{\end{longtable}}%
	%
\renewcommand*{\glossaryheader}{%  Change the table header
	\bfseries Sign & \bfseries Description & \bfseries Unit \\
	\hline
	\endhead}
\renewcommand*{\glossentry}[2]{%  Change the displayed items
\glstarget{##1}{\glossentryname{##1}} %
& \glossentrydesc{##1}% Description
& \glsunit{##1}  \tabularnewline
}
}
\setlength{\glsdescwidth}{3in}
} 
```

Then, in template.tex:

```
\addlisttofrontmatter{\glsnogroupskiptrue\setlength{\glsdescwidth}{0.8\textwidth}\printnoidxglossary[type=main]}
\addlisttofrontmatter{\glsnogroupskiptrue\setlength{\glsdescwidth}{0.8\textwidth}\printnoidxglossary[type=acronym]} 
\addlisttofrontmatter{\printnoidxglossary[type=symbolslist, style=symbunitlong]}
```

I stopped using symbols.tex as well, using only glossary.tex and acronyms.tex, inserting symbols in glossary.tex

Thank you for helping! :+1:
