### ISSUE TITLE
Joining a .tex file in frontmatter - Problem with ToC

### ISSUE THREAD

**Issue by tfcorreia** [joaomlourenco/novathesis#69]
I wrote a motivation and workflow chapter to my thesis and tried to put it on frontmatter.

However, after some bad coding of my part, I finally managed to join a .tex file on \thesisfrontmatter. But there's a small problem when looking at the ToC, and I'm trying to understand what is it.

Printscreen of ToC:
![lmao](https://user-images.githubusercontent.com/28350831/28269775-223430ca-6afb-11e7-934f-0e62352b3ed6.PNG)

The code I put together was copy paste from novathesis.cls, when defining the acknowledgements (bold is what is new):

`\newcommand{\novathesis@acknowledgementsfile}{\@empty}
\newcommand{\acknowledgementsfile}[1]{%
  \renewcommand{\novathesis@acknowledgementsfile}{#1}%
}

**\newcommand{\novathesis@motivationfile}{\@empty}
\newcommand{\motivationfile}[1]{%
  \renewcommand{\novathesis@motivationfile}{#1}%
}**

\newcommand{\printacknowledgements}{%
	\IfFileExists{Chapters/\novathesis@acknowledgementsfile}{%
		\ifthenelse{%
			\equal{\novathesis@opt@docdegree}{bsc}	% bsc
			\OR%
			\equal{\novathesis@opt@docdegree}{msc}	% msc
			\OR%
			\equal{\novathesis@opt@docdegree}{phd}	% phd
		}{% THEN
			\input{Chapters/\novathesis@acknowledgementsfile}%
			\cleardoublepage%
		}{% ELSE
		}%
	}%
	{}%
}
**\newcommand{\printmotivation}{%
	\IfFileExists{Chapters/\novathesis@motivationfile}{%
		\ifthenelse{%
			\equal{\novathesis@opt@docdegree}{bsc}	% bsc
			\OR%
			\equal{\novathesis@opt@docdegree}{msc}	% msc
			\OR%
			\equal{\novathesis@opt@docdegree}{phd}	% phd
		}{% THEN
			\input{Chapters/\novathesis@motivationfile}%
			\cleardoublepage%
		}{% ELSE
		}%
	}%
	{}%
}**`

And here is the code in defining chapters in Motivation.tex:

\chapter*{Motivation and objective}
\label{motivationobj}
\addcontentsline{toc}{chapter}{Motivation and objective}

Example great thesis motivation and objective text.

\vspace{70pt}
{\let\clearpage\relax\chapter*{Workflow}}
\label{workflow}
\addcontentsline{toc}{chapter}{Workflow}

Example magnificent workflow text.

Can't find what may be wrong, maybe it's the \addcontentsline, although if commented these two chapters won't be on ToC..

**Comment by joaomlourenco** [comment]
At a first glance it seems you did everything all right!  👍 
So… What is your problem after all?  It was not clear in your message!

**Comment by tfcorreia** [comment]
I'm sorry! Didn't made it clear. Those little black boxes next to the roman page number. Is that normal?

**Comment by outbound-pt** [comment]
That's just a margin warning that will show as long as the document is set to "draft". They will disappear once you set it to "final".

**Comment by tfcorreia** [comment]
Got it. Thanks! Sorry for the trouble
