### ISSUE TITLE
How to change subfigure formatting?

### ISSUE THREAD

**Issue by outbound-pt** [joaomlourenco/novathesis#70]
Greetings,

Something I've been meaning to do for some time is to change the sub-figure formatting.

As it is it prints out as:
"a One sub-figure"

However, I'd like to format it with an additional right side parenthesis such as:

"a) One sub-figure"

Is this possible, or does it go against the style rules for the NOVA document?

Cumprimentos,

**Comment by tfcorreia** [comment]
A former student had the same question in FB group. The solution was to remove the \RequirePackage{subcaption} on packages.clo and adding a package on template.tex called capt.of.

Unfortunately I can't link to the post itself, but it's from September 12th.

**Comment by outbound-pt** [comment]
Thank you! :)

**Comment by joaomlourenco** [comment]
Closed!
