### ISSUE TITLE
Problem with Bibtex settings, incorrect setting `style`

### ISSUE THREAD

**Issue by ricardogaspar2** [joaomlourenco/novathesis#71]
Since I updated to this new version, I started to have some problems with my citations and references.
I thought it was my fault, but I discovered that it was misconfiguration issue.

The error I got:

```
! Missing number, treated as zero.
<to be read again> 
                   \relax 
l.46 ...caption{Waterfall model~\cite{Villa2016}.}
                                                  
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
```

The incorrect setting is located in the `template.tex` file, in the biblatex settings the `style` property is incorrectly set to **numeric-comp** instead of **numeric**:
https://github.com/joaomlourenco/novathesis/blob/master/LaTeX/template.tex#L71

**Comment by ricardogaspar2** [comment]
Actually, the setting is ok. But the documentation (comments) are not.

My error came from ShareLaTeX. I had to copy my project to load new packages.
https://www.sharelatex.com/learn/Copying_a_project

**Comment by joaomlourenco** [comment]
Solved!
