### ISSUE TITLE
Corrigir texto relativo a PHDPLAN

### ISSUE THREAD

**Issue by ateofilo** [joaomlourenco/novathesis#81]
Em \dissertationstr de "phdplan,pt" colocar um texto algo como: "Plano de dissertação para a obtenção do Grau de Doutor em ...".

Penso que "plano de dissertação" é mais adequado que "plano de tese", pois uma dissertação pode conter mais do que uma tese. Enfim...

**Comment by joaomlourenco** [comment]
Um "plano de dissertação" seria um plano do/para o documento.    O documento em si é um Plano de Tese.
