### ISSUE TITLE
Error when generating template for bachelor at NOVA-IMS

### ISSUE THREAD

**Issue by antoniomnds** [joaomlourenco/novathesis#83]
Console output: [console_output.txt](https://github.com/joaomlourenco/novathesis/files/2193682/console_output.txt)

**Software** : TeXworks version 0.6.2 64-bit; MikTeX 2.9.6730 64-bit
**OS** : Windows 10  17134.165
**Release** : 4.1.0

**Comment by joaomlourenco** [comment]
Fixed.
