### ISSUE TITLE
Rvise the FCSH-NOVA cover (they have a nre logo)

### ISSUE THREAD

**Issue by joaomlourenco** [joaomlourenco/novathesis#85]
https://www.fcsh.unl.pt/media/media-kit

**Comment by tmonteiro2344** [comment]
created branch for WIP

**Comment by tmonteiro2344** [comment]
do we still need the old cover as well as was in the documents provided?
If possible, get the full FCSH directives on thesis formatting.

**Comment by joaomlourenco** [comment]
Hi. Thanks for addressing this issue.  Welcome aboard. 👍 
I am not from FCSH, but I don't think the old cover is still necessary.
The high-quality (vectorial) logos are available in the address above.
I believe there were no changes in the rules (margins, etc) and the template was repeating the rules, just in the logo and cover layout.
Still… If I do find access to the thesis formatting directives for FCSH, I'll let you know.

**Comment by tmonteiro2344** [comment]
Thanks, it's a return for me, after contributing with cd cover and spine
corrections a few years ago :)

Feel free to check the new branch that I created, I still need to check the
margins on MS Office as I'm afraid that on libreoffice some things can
become unformatted.

Do we provide a cd cover for fcsh already?

**Comment by joaomlourenco** [comment]
There is no customized CD cover for FCSH.  I think just FCT-NOVA has a customized CD cover.  :)

**Comment by joaomlourenco** [comment]
Thanks for the pull request. :)
I'll apply it in the asap.
 Two things:
1) Who are you?  :D
2) Would you like to help further by addressing other pending tickets?
Thanks.

**Comment by joaomlourenco** [comment]
Merge concluded.  Thanks again!

**Comment by tmonteiro2344** [comment]
Sure I'll be glad to help whenever I can :)

**Comment by joaomlourenco** [comment]
would you like to take another issue?
