### ISSUE TITLE
[NEW SCHOOL] add support for ITQB

### ISSUE THREAD

**Issue by nunocalaim** [joaomlourenco/novathesis#87]
I found the official guidelines here https://www.itqb.unl.pt/education/PhD%20Programs/itqb-phd-programme/research-project/guidelines-for-writing-the-ph.pdf

But I think the cover needs to be something specific though I cannot find it

**Comment by joaomlourenco** [comment]
Please investigate further and let me know.  I'll add support for ITQB in the near future.

**Comment by nunocalaim** [comment]
I finally found the precise requirements for ITQB thesis:

Excerto do regulamento de doutoramentos do ITQB (2 de Outubro de 2013):
2 — Formato da tese definitiva
Formato — 18 cm (larg.) × 25 cm (alt.)
Espaço entre linhas — 1.5 lines
Tamanho da letra — equivalente a Arial 11
Tamanho da Tese — É desejável que o número de páginas não ultrapasse as 250.
Atenção: Para a elaboração do formato da tese (capa, contracapa e lombada) consultar o link: http://www.itqb.unl.pt/internal/templates/ templates e verificar em Thesis Cover Template
Candidatos que tiveram bolsa da Fundação para a Ciência e a Tecnologia — não esquecer referir na Tese o “apoio financeiro da FCT e do FSE no âmbito do Quadro Comunitário de apoio, SFRH/BD/.../...”

I will try to post on the google groups the specific thesis covers

**Comment by nunocalaim** [comment]
I'm trying to help in making the NOVAthesis support ITQB.

Considering only PhD thesis, ITQB sends you already the cover, aftercover, spine and back on a power point file, They allow you to choose from 4 colors for the cover spine and back, and they want a custom cover figure for your thesis.
If your PhD is done outside ITQB this changes the after-cover in that you need the logo of the institution where you were conducting your research (currently either Instituto Gulbenkian da Ciência or Fundação Champalimaud) preceded by the text: Research work coordinated by:
All text for the cover, spine, after-cover and back should be with font lucida sans
For the inhouse ITQB thesis I can't be sure what the after-cover should look like maybe someone could tell?

With all these specific customizations and color choices I am now wondering if it is practical that we let NOVAthesis redraw all these cover, spine, after-cover or whether we should expect the user to customize the powerpoint they send us and later attach it to the document.

What do you think @joaomlourenco ?

**Comment by joaomlourenco** [comment]
@nunocalaim and @pdMM11, can one of you please share with me the relevant documents (and images/logos) at "http://www.itqb.unl.pt/internal/templates/"?

**Comment by joaomlourenco** [comment]
@pdMM11, fechado na versão 6.9.5.
