### ISSUE TITLE
Bug: Symbols are empty if there are no chapters

### ISSUE THREAD

**Issue by nunocalaim** [joaomlourenco/novathesis#89]
If you change the template.tex by just commenting on the lines

\chapterfile{chapter1}
\chapterfile{chapter2}
\chapterfile{chapter3}

and
\appendixfile{appendix1}
\appendixfile{appendix2}
\annexfile{annex1}

then the symbols list will disappear.

This is a problem because with my custom chapters the symbol list also dissapears

**Comment by joaomlourenco** [comment]
Thank you for your collaboration but this is not a bug. This is a feature (on the philosophy) of LaTeX.  Only references, symbols, glossary entries, etc, that are references in the text will appear in the Index/Glossary list, etc.
If you comment all the chapters they are not referenced and will not show.

**Comment by nunocalaim** [comment]
Thank you, that's interesting. The weird thing is that in the acronyms and glossary the entries are appearing even though the text is not referencing them. 

But I found out that the command \glsaddall seems to include them even though they are not in the text.

Would it make sense to be consistent in including \glsaddall to either all glossary, symbols, references, etc. or on none?
