### ISSUE TITLE
Additional warnings when running the template

### ISSUE THREAD

**Issue by nunocalaim** [joaomlourenco/novathesis#92]
I know it is unnecessary to solve all warnings (see #61) but I am seeing two warnings that I wonder if that means my tex system misses some important fonts:

```
Chapters/chapter2.tex:184: LaTeX Font Warning: Font shape `T1/jkptt/m/sc' undefined(Font)              using `T1/jkptt/m/n' instead on input line 184.
template.tex: LaTeX Font Warning: Some font shapes were not available, defaults substituted.
```

**Comment by joaomlourenco** [comment]
It happens is all the systems I know.  I believe these warnings are not (very) relevant.
