### ISSUE TITLE
Possible bug in novathesis.cls

### ISSUE THREAD

**Issue by ruivalmeida** [joaomlourenco/novathesis#98]
When compiling with appendices, my latexmk complains about line 832, more specifically, it says that \appendixnamepl is not defined. This macro is not defined anywhere in the cls file and is only mentioned in this line. 
Changing \appendixnamepl to \appendixname seems to resolve the issue. Can anyone confirm this?

**Comment by ruivalmeida** [comment]
Just a small note I forgot to say: I have seen this happen on Mac and Ubuntu.

**Comment by flaviomartins** [comment]
Replace fix-babel.clo with the new version from https://github.com/joaomlourenco/novathesis/blob/master/novathesis-files/fix-babel.clo
